/**
 * Auto-convert any local PNG/JPG/JPEG image path to WebP.
 * All product images now have WebP variants generated by scripts/optimize-images.mjs.
 * Falls back to original URL if the path doesn't match a convertible pattern.
 */
function toWebpPath(pathname: string): string | null {
  if (!/\.(png|jpe?g)$/i.test(pathname)) return null;
  return pathname.replace(/\.(png|jpe?g)$/i, ".webp");
}

export function preferLocalWebp(url: string | null | undefined): string {
  if (!url || typeof url !== "string") return "";

  try {
    const parsed = new URL(url, window.location.origin);
    const replacement = toWebpPath(parsed.pathname);
    if (!replacement) return url;
    return `${replacement}${parsed.search}${parsed.hash}`;
  } catch {
    const [pathWithQuery, hash = ""] = url.split("#");
    const [pathname, query = ""] = pathWithQuery.split("?");
    const replacement = toWebpPath(pathname);
    if (!replacement) return url;
    return `${replacement}${query ? `?${query}` : ""}${hash ? `#${hash}` : ""}`;
  }
}

export function preferLocalProductCardWebp(url: string | null | undefined): string {
  if (!url || typeof url !== "string") return "";

  const toCardWebp = (pathname: string) => {
    if (!pathname.startsWith("/images/products/")) return "";
    if (!/\.(png|jpe?g)$/i.test(pathname)) return "";
    return pathname.replace(/\.(png|jpe?g)$/i, ".card.webp");
  };

  try {
    const parsed = new URL(url, window.location.origin);
    const replacement = toCardWebp(parsed.pathname);
    if (!replacement) return preferLocalWebp(url);
    return `${replacement}${parsed.search}${parsed.hash}`;
  } catch {
    const [pathWithQuery, hash = ""] = url.split("#");
    const [pathname, query = ""] = pathWithQuery.split("?");
    const replacement = toCardWebp(pathname);
    if (!replacement) return preferLocalWebp(url);
    return `${replacement}${query ? `?${query}` : ""}${hash ? `#${hash}` : ""}`;
  }
}
