-- Migration ID: blog-language-contamination-pass2-20260902
-- Target:       Neon production, blog_posts
-- Rollback:     rollback.sql (restores content verbatim from the backup table)
--
-- Wave 1 Item 0, residue pass. Pass 1's post-flight guard tested only
-- Han, Kana, Cyrillic and Devanagari, so Hangul, Thai, Hebrew and
-- Latin-Extended contamination passed the gate. Re-scanning with the real guard
-- from shared/script-purity.ts found 8 corrections across 5 articles.
--
-- Two are removals, not recoveries: the fragments recorded as RESEARCH BLOCKED
-- in pass 1 are still unrecoverable, so the corrupted text is dropped and the
-- sentence closes cleanly rather than publishing a guess. Neither is
-- load-bearing, so neither article needs unpublishing.
--
-- Generated by build.mjs, which verified every target against live production
-- and proved the full set leaves 0 violations corpus-wide before emitting.

BEGIN;

DO $$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n FROM blog_posts WHERE is_published;
  IF n <> 80 THEN RAISE EXCEPTION 'expected 80 published posts, found %', n; END IF;
END $$;

CREATE TABLE blog_posts_content_backup_lang_p2_20260902 AS
SELECT id, slug, title, excerpt, content, is_published, now() AS backed_up_at
  FROM blog_posts;

-- Pre-flight: every target must still be present exactly as drafted.
DO $$
DECLARE missing text;
BEGIN
  SELECT string_agg(t.slug || ' :: ' || t.frag, chr(10)) INTO missing
    FROM (VALUES
      ('common-fish-diseases-white-spot', 'לעلاجه بسرعة:'),
      ('american-vs-african-cichlids-differences', 'لتربية 성공ية'),
      ('ph-level-iraqi-tap-water-fish', 'للคลور بكميات زائدة'),
      ('american-vs-african-cichlids-differences', 'التي تمتاز bằngرارها وعدوانيتها'),
      ('neon-tetra-color-care-guide', 'استخدام ط Ard معقم المياه'),
      ('algae-war-guide', 'والمغذيات وCO2</p>'),
      ('neon-tetra-color-care-guide', '<p>"<h2>مقدمة حول أسماك النيون تيترا</h2>'),
      ('neon-tetra-color-care-guide', 'عالية الجودة.</p>"</p>')
    ) AS t(slug, frag)
    LEFT JOIN blog_posts b ON b.slug = t.slug
   WHERE b.id IS NULL OR position(t.frag in b.content) = 0;
  IF missing IS NOT NULL THEN
    RAISE EXCEPTION 'live content changed since drafting; missing targets: %', missing;
  END IF;
END $$;

-- common-fish-diseases-white-spot (1 correction)
--   high · Hebrew ל+ע substituted 1:1 for Arabic ل+ع. The surviving 'لاجه' plus that prefix gives 'لعلاجه' and nothing else, and the next clause is the treatment protocol ('1. ارفع درجة حرارة السخان').
UPDATE blog_posts SET content = replace(content, 'לעلاجه بسرعة:', 'لعلاجه بسرعة:')
 WHERE id = '2141ca04-398a-4303-9a91-c40bf9069fd9';

-- american-vs-african-cichlids-differences (2 corrections)
--   high · 성공 = 'success'. The same article already writes 'ظروف معينة لتربية ناجحة' verbatim twice, so the intended wording is attested in the row itself. Pass 1 fixed the Han spelling 成功 of this same phrase and missed the Hangul one.
--   removal — meaning not recoverable · UNRECOVERABLE. Vietnamese 'bằng' displaced a prefix; the surviving 'رارها' fits باستمرارها / بإصرارها / باحمرارها / بفرارها and the bullet is about behaviour, so no reading is safely inferable. The corrupted trait is dropped and the sentence keeps only what survived intact ('وعدوانيتها'), which is also the well-attested trait of African rift-lake cichlids. Grammatical, and no claim is invented. The bullet is not load-bearing: the article's behaviour comparison stands without it.
UPDATE blog_posts SET content = replace(replace(content, 'لتربية 성공ية', 'لتربية ناجحة'), 'التي تمتاز bằngرارها وعدوانيتها', 'التي تمتاز بعدوانيتها')
 WHERE id = '0f433d30-a234-4fa8-a792-0769adc3307a';

-- ph-level-iraqi-tap-water-fish (1 correction)
--   high · Thai ค+ล substituted 1:1 for Arabic ك+ل inside 'للكلور' (chlorine). The paragraph is about over-chlorinated Iraqi tap water. Pass 1 made the identical repair on a Cyrillic spelling ('والكлор،' → 'والكلور،').
UPDATE blog_posts SET content = replace(content, 'للคลور بكميات زائدة', 'للكلور بكميات زائدة')
 WHERE id = '70512819-ab15-465f-a0e9-85a8f838d6f0';

-- neon-tetra-color-care-guide (3 corrections)
--   removal — meaning not recoverable · UNRECOVERABLE. 'ط Ard' is two fragments with a space in a list of water-quality equipment; it could be a product type, a brand or a verb and the list item gives no further signal. Removing it leaves 'استخدام معقم المياه لمنع تلوث المياه' — complete, grammatical, and exactly the advice the sentence already carried. Nothing is invented.
--   high · The whole body was persisted wrapped in a paragraph and a literal double quote, so the page opens with a stray " before its first heading and block elements sit inside a <p>. Removes the wrapper opening only.
--   high · Closing half of the same stray wrapper — a trailing " and an unmatched </p>.
UPDATE blog_posts SET content = replace(replace(replace(content, 'استخدام ط Ard معقم المياه', 'استخدام معقم المياه'), '<p>"<h2>مقدمة حول أسماك النيون تيترا</h2>', '<h2>مقدمة حول أسماك النيون تيترا</h2>'), 'عالية الجودة.</p>"</p>', 'عالية الجودة.</p>')
 WHERE id = '0494f8eb-878a-48a1-ba43-927a8db81d2e';

-- algae-war-guide (1 correction)
--   high · NOT corruption. 'وCO2' is correct Arabic — the conjunction و proclitic on a Latin technical term. It trips SPLICED_LATIN, which fails closed on any Latin run welded to an Arabic letter because the proclitics ب and ل are exactly how real corruption arrived ('بbehind', 'لallow'). Relaxing the rule would readmit those, so the space is added here instead and the guard stays strict. Reads identically.
UPDATE blog_posts SET content = replace(content, 'والمغذيات وCO2</p>', 'والمغذيات و CO2</p>')
 WHERE id = '20296a10-0f15-40a5-a032-9e917af50529';

-- Post-flight. Unlike pass 1 this covers every script the guard rejects:
-- Han, Kana, Hangul, Cyrillic, Devanagari, Thai, Hebrew and Latin-Extended.
DO $$
DECLARE
  leftover int;
  sample text;
  bad text := '[\u4e00-\u9fff\u3040-\u30ff\uac00-\ud7af\u0400-\u04ff\u0900-\u097f\u0e00-\u0e7f\u0590-\u05ff\u0100-\u024f\u1e00-\u1eff]';
BEGIN
  SELECT count(*), string_agg(slug, ', ') INTO leftover, sample
    FROM blog_posts WHERE is_published AND content ~ bad;
  IF leftover <> 0 THEN
    RAISE EXCEPTION '% published articles still carry stray script: %', leftover, sample;
  END IF;
END $$;

-- Post-flight: nothing outside content may move, and exactly the drafted rows
-- may change.
DO $$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n
    FROM blog_posts b JOIN blog_posts_content_backup_lang_p2_20260902 k USING (id)
   WHERE b.title IS DISTINCT FROM k.title
      OR b.excerpt IS DISTINCT FROM k.excerpt
      OR b.is_published IS DISTINCT FROM k.is_published;
  IF n <> 0 THEN RAISE EXCEPTION '% rows had title/excerpt/is_published altered', n; END IF;

  SELECT count(*) INTO n
    FROM blog_posts b JOIN blog_posts_content_backup_lang_p2_20260902 k USING (id)
   WHERE b.content IS DISTINCT FROM k.content;
  IF n <> 5 THEN RAISE EXCEPTION 'expected 5 content rewrites, got %', n; END IF;
END $$;

COMMIT;
