import { defineConfig } from "drizzle-kit";
import * as dotenv from "dotenv";

dotenv.config({ path: ".env.local" });
dotenv.config();

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL, ensure the database is provisioned");
}

export default defineConfig({
  out: "./migrations",
  schema: ["./shared/schema.ts", "./shared/operations-schema.ts"],
  dialect: "postgresql",
  dbCredentials: {
    url: process.env.DATABASE_URL,
  },
  tablesFilter: [
    "users",
    "password_reset_tokens",
    "products",
    "orders",
    "shipping_settlements",
    "product_cost_history",
    "expenses",
    "reviews",
    "review_ratings",
    "express_sessions",
    "discounts",
    "store_audit_logs",
    "coupons",
    "cart_items",
    "favorites",
    "fish_species",
    "gallery_submissions",
    "gallery_votes",
    "categories",
    "order_items_relational",
    "payments",
    "translations",
    "user_addresses",
    "gallery_prizes",
    "newsletter_subscriptions",
    "email_logs",
    "journey_plans",
    "referral_codes",
    "referrals",
    "login_attempts",
    "blocked_ips",
    "page_views",
    "sales_stats",
    "email_campaigns",
    "push_subscriptions",
    "chat_messages",
    "support_tickets",
    "product_interactions",
    "product_embeddings",
    "price_history",
    "search_queries",
    "customer_profiles",
    "image_analyses",
    "sentiment_history",
    "predicted_needs",
    "churn_predictions",
    "ai_email_metrics",
    "inventory_recommendations",
    "auto_orders",
    "accounting_manual_adjustments",
    "accounting_review_flags",
    "accounting_audit_trail",
    "accounting_period_closes",
    "ai_agent_settings",
    "store_social_interactions",
    "settings",
    "data_source_registry",
    "database_repair_runs",
    "database_repair_findings",
    "inventory_legacy_snapshots",
    "product_variant_reconciliation",
    "inventory_locations",
    "inventory_reconciliations",
    "inventory_movements",
    "suppliers",
    "supplier_products",
    "supplier_quotes",
    "supplier_quote_items",
    "purchase_orders",
    "purchase_order_items",
    "goods_receipts",
    "goods_receipt_items",
    "landed_cost_allocations",
    "payment_events",
    "cash_settlements",
    "cash_settlement_items",
    "order_financial_adjustments"
  ]
});
