-- Migration ID: blog-claims-truth-pass1-20260902
-- Target:       Neon production, blog_posts
-- Rollback:     rollback.sql (restores content verbatim from the backup table)
-- Depends on:   docs/audit/neon-tetra-editorial/migration.sql
--
-- Corpus-wide claims audit, batch 1. This is a different defect class from
-- script contamination: the generator asserted business facts it had no source
-- for. Ground truth is the live catalogue, the governorate list, the shipping
-- constants and the published policy pages. See audit.md for the full ledger,
-- including the claims that were checked and KEPT.
--
-- 35 corrections across 22 articles.
-- Generated by build.mjs, which verified every target against live production
-- and proved the banned claims are gone corpus-wide before emitting.

BEGIN;

DO $$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n FROM blog_posts WHERE is_published;
  IF n <> 80 THEN RAISE EXCEPTION 'expected 80 published posts, found %', n; END IF;
END $$;

-- Pre-flight: the neon-tetra editorial migration must already be applied. It
-- owns the one remaining superlative sentence that this pass's post-flight
-- guard checks for corpus-wide.
DO $$
DECLARE c text;
BEGIN
  SELECT content INTO c FROM blog_posts WHERE slug = 'neon-tetra-color-care-guide';
  IF c IS NULL OR position('أفضل وأكبر' in c) > 0 THEN
    RAISE EXCEPTION 'neon-tetra editorial migration has not been applied yet; run it first';
  END IF;
END $$;

CREATE TABLE blog_posts_backup_claims_p1_20260902 AS
SELECT id, slug, title, excerpt, content, is_published, now() AS backed_up_at
  FROM blog_posts;

-- Pre-flight: every target must still be present at its expected count.
DO $$
DECLARE bad text;
BEGIN
  SELECT string_agg(t.slug || ' :: ' || left(t.frag, 60), chr(10)) INTO bad
    FROM (VALUES
      ('saltwater-vs-freshwater-aquarium-beginners', 'يجب دائمًا اختيار الأسماك المالحة من مورد موثوق به، مثل AQUAVO، الذي يوفر الأسماك المالحة عالية الجودة وضمانًا لمدة عام.', 1),
      ('saltwater-vs-freshwater-aquarium-beginners', 'AQUAVO هي المورد الأول للمستلزمات Aquarium في العراق، وتوفر خدمات شاملة، بما في ذلك:', 1),
      ('saltwater-vs-freshwater-aquarium-beginners', '  <li>ضمان لمدة عام على الأسماك المالحة.</li>
', 1),
      ('how-to-get-rid-of-green-algae', 'مثل أسماك الكوريدوراس والأوتوسينكلس أسنينا المتوفرة في أكوافو، أو حلزونات النيريت (Nerite Snails)', 1),
      ('turtles-with-aquarium-fish', 'حوض مائي للأسماك وحوض (تيراريوم/أكواتيراريوم) للسلاحف. كلاهما متوفر في AQUAVO مع كل المستلزمات.', 1),
      ('real-vs-fake-plants-iraq', ' يمكنك إيجاد هذه الأنواع في متجرنا قسم "النباتات المائية".', 1),
      ('saltwater-vs-freshwater-aquarium-beginners', '  <li>منتجات عالية الجودة مستوردة من الخارج.</li>', 1),
      ('koi-fish-outdoor-pond-building-tips', 'يمكنك العثور على أنظمة ترشيح عالية الجودة في متجر <strong>AQUAVO</strong>، الذي يُعتبر المورد الأول والرئيسي للمنتجات المائية في العراق. يُقدم <strong>AQUAVO</strong> ضمانات وخدمات توصيل إلى جميع أنحاء البلاد، ويركز على توفير أفضل المنتجات المستوردة لضمان صحة ورفاهية أسماك الكوي.', 1),
      ('calculate-aquarium-capacity-liters', 'يمكنك زيارة موقع شركة AQUAVO على الإنترنت، أو زيارة أحد فروعها في العراق، لاستشارة خبراء الشركة وشراء كل ما يحتاجه مربي الأسماك.', 1),
      ('calculate-aquarium-capacity-liters', 'تقدم شركة AQUAVO منتجات مستوردة ذات جودة عالية، مما يضمن لك تجربة مرضية وسهلة في تربية الأسماك.', 1),
      ('aquarium-planted-led-lighting-guide', 'لتفادي نمو الطحالب، اضبط مصباح حوضك عن طريق شاشة التحكم الذكية من متجرنا لمدة 7 ساعات باليوم فقط.', 1),
      ('driftwood-preparation-yellow-water-fix', ' يمكنك أيضاً استخدام منتجات AQUAVO لتعقيم الأخشاب المتحجرة، مثل محلول التعقيم الذي نقدمه في متجرنا.', 1),
      ('amazon-biotope-aquarium-setup', 'يمكن التغلب على هذه التحديات باستخدام <strong>مضخات احتياطية</strong> و<strong>أنظمة التبريد</strong> التي يمكن الحصول عليها من متجر AQUAVO.', 1),
      ('co2-system-planted-aquarium-guide', '   <li>نظام ثاني أكسيد الكربون عالي الجودة.</li>
   <li>ضمان على جميع المنتجات.</li>
', 1),
      ('hardscape-rock-arrangement-visual-depth', ' مع وجود warranties وضمانات لمدة تصل إلى 5 سنوات على منتجاتنا، يمكن لزباين AQUAVO التأكد من حصولهم على أفضل المنتجات والخدمات.', 1),
      ('freshwater-pufferfish-care-guide', 'في AQUAVO، نقدم لك "<strong>ضمان صحي</strong>" و "<strong>دعم فني</strong>" لجميع منتجاتنا، بالإضافة إلى "<strong>توصيل سريع</strong>" إلى جميع "<strong>المحافظات</strong>" في العراق.', 1),
      ('tetra-food-vs-budget-brands-comparison', '
<p>بالإضافة إلى ذلك، يضمن AQUAVO جودة مياه الصنبور المستخدمة في حاوية الأسماك، حيث يتم تقليل نسبة الكلور إلى أدنى حد، مما يضمن صحة الأسماك ورفاهيتها.</p>', 1),
      ('tetra-food-vs-budget-brands-comparison', 'مع ضمانات وضمان جودة المنتجات، وتوصيل المنتجات إلى 18 محافظة، يصبح اختيار العلف الصحيح أمراً سهلاً وآمناً.', 1),
      ('ammonia-spike-emergency-treatment', 'AQUAVO هي أول متجر احترافي لأحواض السمك في العراق، وتقدم مجموعة واسعة من المنتجات عالية الجودة المستوردة من جميع أنحاء العالم. تقدم AQUAVO ضمانات على منتجاتها، وتقدم خدمة التوصيل إلى 18 محافظة في العراق.', 1),
      ('flowerhorn-breeding-nuchal-hump-secrets', 'AQUAVO، كأول متجر محترف لأسماك الزينة في العراق، يلعب دورًا هامًا في توفير كل ما يحتاجه هواة تربية الأسماك، بما في ذلك أسماك الفلورهورن.', 1),
      ('flowerhorn-breeding-nuchal-hump-secrets', 'مع ضمانات على المنتجات وتوصيل المنتجات إلى جميع أنحاء العراق، بما في ذلك 18 محافظة، يعتبر AQUAVO شريكًا موثوقًا لجميع هواة الأسماك.', 1),
      ('flowerhorn-breeding-nuchal-hump-secrets', 'التي توفر أنظمة ترشيح عالية الجودة وضمانات على المنتجات.', 1),
      ('guppy-fish-care-breeding-guide', 'الرقائق (Flakes) عالية الجودة من ماركات موثوقة (تباع في منيو أكوافو)', 1),
      ('driftwood-preparation-yellow-water-fix', 'يمكن معالجة إصفرار الماء باستخدام مواد كيميائية مثل الكلور أو الزيوليت.', 1),
      ('hardscape-rock-arrangement-visual-depth', 'في دائرة حول نقطة trung tâm.', 1),
      ('hardscape-rock-arrangement-visual-depth', 'شكل تفرع يمتد من نقطة trung tâm.', 1),
      ('hardscape-rock-arrangement-visual-depth', 'هواة صيدلة الأسماك', 6),
      ('flowerhorn-breeding-nuchal-hump-secrets', 'بسبب yüksek نسبة الكلور', 1),
      ('ornamental-fish-import-middle-east-origins', 'ولكن يمكن phânها إلى ثلاث فئات رئيسية:', 1),
      ('driftwood-preparation-yellow-water-fix', 'لتجف hoànًا', 1),
      ('diy-3d-aquarium-background', 'يجب também مراعاة', 1),
      ('amazon-sword-plant-care-propagation', 'التي تتناسب مع ظروف votre Aquarium.', 1),
      ('corydoras-types-best-cleaner-fish', 'دورًا هامًا في guarantein salud الحوض', 1),
      ('why-fish-die-suddenly-rescue-guide', 'جودة الماء هو faktor آخر مهم', 1),
      ('black-beard-algae-removal-steps', 'لا ت	require إلىخبرة كبيرة، بل يتطلب', 1)
    ) AS t(slug, frag, want)
    LEFT JOIN blog_posts b ON b.slug = t.slug
   WHERE b.id IS NULL
      OR (length(b.content) - length(replace(b.content, t.frag, ''))) / nullif(length(t.frag), 0) <> t.want;
  IF bad IS NOT NULL THEN
    RAISE EXCEPTION 'live content changed since drafting; bad targets: %', bad;
  END IF;
END $$;

-- saltwater-vs-freshwater-aquarium-beginners (4 corrections)
--   REMOVE · AQUAVO sells no live fish at all, marine or freshwater, and no one-year fish guarantee exists. Two false claims in one sentence.
--   REMOVE · Unsupported 'first supplier in Iraq' claim; also drops a stray English word left mid-sentence.
--   REMOVE · A one-year warranty on live fish AQUAVO does not sell. return-policy.tsx limits any warranty to a product whose page names it explicitly.
--   REMOVE · Undocumented sourcing claim, replaced with categories that demonstrably exist.
UPDATE blog_posts SET content = replace(replace(replace(replace(content, 'يجب دائمًا اختيار الأسماك المالحة من مورد موثوق به، مثل AQUAVO، الذي يوفر الأسماك المالحة عالية الجودة وضمانًا لمدة عام.', 'يجب دائمًا اختيار الأسماك المالحة من مورد مختص، والتأكد من صحتها وحالتها قبل الشراء.'), 'AQUAVO هي المورد الأول للمستلزمات Aquarium في العراق، وتوفر خدمات شاملة، بما في ذلك:', 'AQUAVO متجر عراقي مختص بمستلزمات الأحواض، ويوفر:'), '  <li>ضمان لمدة عام على الأسماك المالحة.</li>
', ''), '  <li>منتجات عالية الجودة مستوردة من الخارج.</li>', '  <li>مستلزمات فلترة وتهوية ومعالجة مياه.</li>')
 WHERE slug = 'saltwater-vs-freshwater-aquarium-beginners';

-- how-to-get-rid-of-green-algae (1 correction)
--   REMOVE · Claims live algae-eating fish and snails are stocked. They are not — the catalogue carries no live animals. The husbandry advice itself is sound and is kept.
UPDATE blog_posts SET content = replace(content, 'مثل أسماك الكوريدوراس والأوتوسينكلس أسنينا المتوفرة في أكوافو، أو حلزونات النيريت (Nerite Snails)', 'مثل أسماك الكوريدوراس والأوتوسينكلس، أو حلزونات النيريت (Nerite Snails)')
 WHERE slug = 'how-to-get-rid-of-green-algae';

-- turtles-with-aquarium-fish (1 correction)
--   REMOVE · AQUAVO stocks two aquariums and no terrarium or turtle equipment. 'Both available with all supplies' is invented inventory.
UPDATE blog_posts SET content = replace(content, 'حوض مائي للأسماك وحوض (تيراريوم/أكواتيراريوم) للسلاحف. كلاهما متوفر في AQUAVO مع كل المستلزمات.', 'حوض مائي للأسماك وحوض (تيراريوم/أكواتيراريوم) للسلاحف.')
 WHERE slug = 'turtles-with-aquarium-fish';

-- real-vs-fake-plants-iraq (1 correction)
--   REMOVE · Invents both a product line and a store section. AQUAVO sells no live plants and has no النباتات المائية category; its 11 categories carry only substrate and anchoring accessories.
UPDATE blog_posts SET content = replace(content, ' يمكنك إيجاد هذه الأنواع في متجرنا قسم "النباتات المائية".', '')
 WHERE slug = 'real-vs-fake-plants-iraq';

-- koi-fish-outdoor-pond-building-tips (1 correction)
--   REMOVE · 'The first and principal supplier of aquatic products in Iraq' has no source, and the blanket warranty plus the import claim are unsupported. Filtration and water treatment are real categories, and the delivery claim is verified, so both are kept.
UPDATE blog_posts SET content = replace(content, 'يمكنك العثور على أنظمة ترشيح عالية الجودة في متجر <strong>AQUAVO</strong>، الذي يُعتبر المورد الأول والرئيسي للمنتجات المائية في العراق. يُقدم <strong>AQUAVO</strong> ضمانات وخدمات توصيل إلى جميع أنحاء البلاد، ويركز على توفير أفضل المنتجات المستوردة لضمان صحة ورفاهية أسماك الكوي.', 'يمكنك العثور على أنظمة ترشيح ومعالجات مياه في متجر <strong>AQUAVO</strong>، مع توصيل إلى 18 محافظة في العراق.')
 WHERE slug = 'koi-fish-outdoor-pond-building-tips';

-- calculate-aquarium-capacity-liters (2 corrections)
--   REMOVE · Invents physical branches. Nothing in the codebase or the policy pages describes a physical location; checkout is delivery-only to 18 governorates.
--   REMOVE · The sourcing claim is undocumented anywhere; replaced with categories that demonstrably exist (18, 13 and 13 SKUs).
UPDATE blog_posts SET content = replace(replace(content, 'يمكنك زيارة موقع شركة AQUAVO على الإنترنت، أو زيارة أحد فروعها في العراق، لاستشارة خبراء الشركة وشراء كل ما يحتاجه مربي الأسماك.', 'يمكنك زيارة موقع AQUAVO على الإنترنت لشراء ما يحتاجه مربي الأسماك.'), 'تقدم شركة AQUAVO منتجات مستوردة ذات جودة عالية، مما يضمن لك تجربة مرضية وسهلة في تربية الأسماك.', 'تقدم AQUAVO مستلزمات أحواض متنوعة تغطي الفلترة والتهوية ومعالجة المياه.')
 WHERE slug = 'calculate-aquarium-capacity-liters';

-- aquarium-planted-led-lighting-guide (1 correction)
--   REMOVE · No smart controller exists; the الإضاءة category holds exactly one product, a 3.5 W LED bar. The 7-hour advice stands on its own and is kept.
UPDATE blog_posts SET content = replace(content, 'لتفادي نمو الطحالب، اضبط مصباح حوضك عن طريق شاشة التحكم الذكية من متجرنا لمدة 7 ساعات باليوم فقط.', 'لتفادي نمو الطحالب، اضبط إضاءة حوضك على 7 ساعات في اليوم فقط.')
 WHERE slug = 'aquarium-planted-led-lighting-guide';

-- driftwood-preparation-yellow-water-fix (3 corrections)
--   REMOVE · No sterilising solution in the catalogue. The boiling method the same paragraph gives is the real procedure and is kept.
--   REMOVE · Telling a reader to put chlorine in an aquarium is a fish-health hazard and contradicts every other article in the corpus, which treats chlorine as the thing to remove. Activated carbon is the real remedy for tannin staining, and is stocked.
--   CORRECT · Vietnamese 'hoàn', from 'hoàn toàn' = completely. The Arabic accusative ending ًا survived, which is exactly how تماماً is written.
UPDATE blog_posts SET content = replace(replace(replace(content, ' يمكنك أيضاً استخدام منتجات AQUAVO لتعقيم الأخشاب المتحجرة، مثل محلول التعقيم الذي نقدمه في متجرنا.', ''), 'يمكن معالجة إصفرار الماء باستخدام مواد كيميائية مثل الكلور أو الزيوليت.', 'يمكن معالجة إصفرار الماء بالكربون النشط مع تغييرات ماء دورية.'), 'لتجف hoànًا', 'لتجف تماماً')
 WHERE slug = 'driftwood-preparation-yellow-water-fix';

-- amazon-biotope-aquarium-setup (1 correction)
--   REMOVE · Neither backup pumps nor cooling systems exist in the catalogue — zero matches across all 11 categories.
UPDATE blog_posts SET content = replace(content, 'يمكن التغلب على هذه التحديات باستخدام <strong>مضخات احتياطية</strong> و<strong>أنظمة التبريد</strong> التي يمكن الحصول عليها من متجر AQUAVO.', 'يمكن التغلب على هذه التحديات بمصدر طاقة احتياطي ومراقبة حرارة الحوض عن قرب في الصيف.')
 WHERE slug = 'amazon-biotope-aquarium-setup';

-- co2-system-planted-aquarium-guide (1 correction)
--   REMOVE · AQUAVO sells no CO2 system — zero matches. The blanket product warranty is separately contradicted by return-policy.tsx.
UPDATE blog_posts SET content = replace(content, '   <li>نظام ثاني أكسيد الكربون عالي الجودة.</li>
   <li>ضمان على جميع المنتجات.</li>
', '   <li>مستلزمات الإضاءة والفلترة والتسميد للأحواض المزروعة.</li>
')
 WHERE slug = 'co2-system-planted-aquarium-guide';

-- hardscape-rock-arrangement-visual-depth (4 corrections)
--   REMOVE · A five-year warranty. return-policy.tsx caps it at a six-month limited warranty, only where a product page names it, and why-aquavo.tsx says explicitly that no document or warranty is generalised across the store. Also carries a stray English word.
--   CORRECT · Vietnamese 'trung tâm' = centre. Both occurrences; the surrounding text is about arranging rocks around and out from a central point, so the meaning is attested.
--   CORRECT · Second occurrence of the same Vietnamese fragment, in the adjacent list item.
--   CORRECT · صيدلة is pharmacy. The corpus writes هواة تربية الأسماك throughout.
UPDATE blog_posts SET content = replace(replace(replace(replace(content, ' مع وجود warranties وضمانات لمدة تصل إلى 5 سنوات على منتجاتنا، يمكن لزباين AQUAVO التأكد من حصولهم على أفضل المنتجات والخدمات.', ''), 'في دائرة حول نقطة trung tâm.', 'في دائرة حول نقطة مركزية.'), 'شكل تفرع يمتد من نقطة trung tâm.', 'شكل تفرع يمتد من نقطة مركزية.'), 'هواة صيدلة الأسماك', 'هواة تربية الأسماك')
 WHERE slug = 'hardscape-rock-arrangement-visual-depth';

-- freshwater-pufferfish-care-guide (1 correction)
--   REMOVE · A 'health guarantee' on all products is invented, and doubly wrong on a page about buying live pufferfish. Support and delivery are real and are kept.
UPDATE blog_posts SET content = replace(content, 'في AQUAVO، نقدم لك "<strong>ضمان صحي</strong>" و "<strong>دعم فني</strong>" لجميع منتجاتنا، بالإضافة إلى "<strong>توصيل سريع</strong>" إلى جميع "<strong>المحافظات</strong>" في العراق.', 'في AQUAVO، نوفر <strong>دعم فني</strong> و<strong>توصيل سريع</strong> إلى <strong>18 محافظة</strong> في العراق.')
 WHERE slug = 'freshwater-pufferfish-care-guide';

-- tetra-food-vs-budget-brands-comparison (2 corrections)
--   REMOVE · Claims AQUAVO guarantees the quality of the reader's municipal tap water. A store cannot do this, and nothing in the corpus or the code suggests it tries to.
--   CORRECT · Blanket product-quality guarantee removed; the delivery claim is verified and kept.
UPDATE blog_posts SET content = replace(replace(content, '
<p>بالإضافة إلى ذلك، يضمن AQUAVO جودة مياه الصنبور المستخدمة في حاوية الأسماك، حيث يتم تقليل نسبة الكلور إلى أدنى حد، مما يضمن صحة الأسماك ورفاهيتها.</p>', ''), 'مع ضمانات وضمان جودة المنتجات، وتوصيل المنتجات إلى 18 محافظة، يصبح اختيار العلف الصحيح أمراً سهلاً وآمناً.', 'مع التوصيل إلى 18 محافظة، يصبح الحصول على العلف المناسب أسهل.')
 WHERE slug = 'tetra-food-vs-budget-brands-comparison';

-- ammonia-spike-emergency-treatment (1 correction)
--   REMOVE · 'First professional aquarium store in Iraq' has no source; nor does the worldwide-import claim; nor the blanket warranty. The delivery claim is verified and kept.
UPDATE blog_posts SET content = replace(content, 'AQUAVO هي أول متجر احترافي لأحواض السمك في العراق، وتقدم مجموعة واسعة من المنتجات عالية الجودة المستوردة من جميع أنحاء العالم. تقدم AQUAVO ضمانات على منتجاتها، وتقدم خدمة التوصيل إلى 18 محافظة في العراق.', 'AQUAVO متجر عراقي مختص بمستلزمات الأحواض، ويوفر التوصيل إلى 18 محافظة في العراق.')
 WHERE slug = 'ammonia-spike-emergency-treatment';

-- flowerhorn-breeding-nuchal-hump-secrets (4 corrections)
--   REMOVE · Same unsupported 'first' claim, and 'everything a keeper needs, including flowerhorn fish' implies AQUAVO sells the fish.
--   CORRECT · Blanket warranty removed; verified delivery kept.
--   CORRECT · Blanket warranty removed; filtration and water treatment are real categories (18 and 13 SKUs).
--   CORRECT · Turkish 'yüksek' = high. The sentence is about high chlorine in drinking water.
UPDATE blog_posts SET content = replace(replace(replace(replace(content, 'AQUAVO، كأول متجر محترف لأسماك الزينة في العراق، يلعب دورًا هامًا في توفير كل ما يحتاجه هواة تربية الأسماك، بما في ذلك أسماك الفلورهورن.', 'AQUAVO متجر عراقي مختص يوفر مستلزمات تربية أسماك الزينة.'), 'مع ضمانات على المنتجات وتوصيل المنتجات إلى جميع أنحاء العراق، بما في ذلك 18 محافظة، يعتبر AQUAVO شريكًا موثوقًا لجميع هواة الأسماك.', 'مع التوصيل إلى 18 محافظة في العراق.'), 'التي توفر أنظمة ترشيح عالية الجودة وضمانات على المنتجات.', 'التي توفر أنظمة ترشيح ومعالجات مياه.'), 'بسبب yüksek نسبة الكلور', 'بسبب ارتفاع نسبة الكلور')
 WHERE slug = 'flowerhorn-breeding-nuchal-hump-secrets';

-- guppy-fish-care-breeding-guide (1 correction)
--   REMOVE · AQUAVO stocks 13 fish foods but no flake product. The feeding advice is correct and is kept without the availability claim.
UPDATE blog_posts SET content = replace(content, 'الرقائق (Flakes) عالية الجودة من ماركات موثوقة (تباع في منيو أكوافو)', 'الرقائق (Flakes) عالية الجودة من ماركات موثوقة')
 WHERE slug = 'guppy-fish-care-breeding-guide';

-- ornamental-fish-import-middle-east-origins (1 correction)
--   CORRECT · Vietnamese 'phân' = divide. Followed immediately by a three-item list, so the meaning is fixed by the structure.
UPDATE blog_posts SET content = replace(content, 'ولكن يمكن phânها إلى ثلاث فئات رئيسية:', 'ولكن يمكن تقسيمها إلى ثلاث فئات رئيسية:')
 WHERE slug = 'ornamental-fish-import-middle-east-origins';

-- diy-3d-aquarium-background (1 correction)
--   CORRECT · Portuguese 'também' = also.
UPDATE blog_posts SET content = replace(content, 'يجب também مراعاة', 'يجب أيضاً مراعاة')
 WHERE slug = 'diy-3d-aquarium-background';

-- amazon-sword-plant-care-propagation (1 correction)
--   CORRECT · French 'votre' = your, welded to an English noun.
UPDATE blog_posts SET content = replace(content, 'التي تتناسب مع ظروف votre Aquarium.', 'التي تتناسب مع ظروف حوضك.')
 WHERE slug = 'amazon-sword-plant-care-propagation';

-- corydoras-types-best-cleaner-fish (1 correction)
--   CORRECT · Spanish 'salud' = health, preceded by a malformed pseudo-word for 'guarantee'.
UPDATE blog_posts SET content = replace(content, 'دورًا هامًا في guarantein salud الحوض', 'دورًا هامًا في الحفاظ على صحة الحوض')
 WHERE slug = 'corydoras-types-best-cleaner-fish';

-- why-fish-die-suddenly-rescue-guide (1 correction)
--   CORRECT · 'faktor' = factor. The Arabic copula is adjusted so the sentence stays grammatical.
UPDATE blog_posts SET content = replace(content, 'جودة الماء هو faktor آخر مهم', 'جودة الماء عامل آخر مهم')
 WHERE slug = 'why-fish-die-suddenly-rescue-guide';

-- black-beard-algae-removal-steps (1 correction)
--   CORRECT · English 'require' spliced onto an Arabic prefix, plus a welded إلىخبرة and a gender disagreement in the following verb.
UPDATE blog_posts SET content = replace(content, 'لا ت	require إلىخبرة كبيرة، بل يتطلب', 'لا تتطلب خبرة كبيرة، بل تتطلب')
 WHERE slug = 'black-beard-algae-removal-steps';

-- Post-flight: the banned claims must be gone from every published article.
DO $$
DECLARE hit text;
BEGIN
  SELECT string_agg(slug, ', ') INTO hit FROM blog_posts WHERE is_published AND content LIKE '%' || 'أفضل وأكبر' || '%';
  IF hit IS NOT NULL THEN RAISE EXCEPTION 'superlative survives in: %', hit; END IF;
  SELECT string_agg(slug, ', ') INTO hit FROM blog_posts WHERE is_published AND content LIKE '%' || 'أول متجر' || '%';
  IF hit IS NOT NULL THEN RAISE EXCEPTION 'first-in-Iraq survives in: %', hit; END IF;
  SELECT string_agg(slug, ', ') INTO hit FROM blog_posts WHERE is_published AND content LIKE '%' || 'المورد الأول' || '%';
  IF hit IS NOT NULL THEN RAISE EXCEPTION 'first-supplier survives in: %', hit; END IF;
  SELECT string_agg(slug, ', ') INTO hit FROM blog_posts WHERE is_published AND content LIKE '%' || 'فروعها' || '%';
  IF hit IS NOT NULL THEN RAISE EXCEPTION 'physical branches survives in: %', hit; END IF;
  SELECT string_agg(slug, ', ') INTO hit FROM blog_posts WHERE is_published AND content LIKE '%' || 'ضمان صحي' || '%';
  IF hit IS NOT NULL THEN RAISE EXCEPTION 'health guarantee survives in: %', hit; END IF;
  SELECT string_agg(slug, ', ') INTO hit FROM blog_posts WHERE is_published AND content LIKE '%' || '5 سنوات على منتجاتنا' || '%';
  IF hit IS NOT NULL THEN RAISE EXCEPTION '5-year warranty survives in: %', hit; END IF;
END $$;

-- Post-flight: nothing outside content may move, and exactly the drafted rows
-- may change.
DO $$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n
    FROM blog_posts b JOIN blog_posts_backup_claims_p1_20260902 k USING (id)
   WHERE b.title IS DISTINCT FROM k.title
      OR b.excerpt IS DISTINCT FROM k.excerpt
      OR b.is_published IS DISTINCT FROM k.is_published;
  IF n <> 0 THEN RAISE EXCEPTION '% rows had title/excerpt/is_published altered', n; END IF;

  SELECT count(*) INTO n
    FROM blog_posts b JOIN blog_posts_backup_claims_p1_20260902 k USING (id)
   WHERE b.content IS DISTINCT FROM k.content;
  IF n <> 22 THEN RAISE EXCEPTION 'expected 22 content rewrites, got %', n; END IF;
END $$;

COMMIT;
