-- 0054_accounting_fulfillment_readiness.sql
-- Fulfillment journals, opening inventory, readiness and two-stage period close.
BEGIN;

CREATE OR REPLACE FUNCTION public.post_order_fulfillment_journal(p_order_id text) RETURNS text LANGUAGE plpgsql AS $$
DECLARE f public.order_accounting_facts%ROWTYPE;o public.orders%ROWTYPE;v_entry_id text;v_events bigint;v_bad bigint;v_cost numeric;
BEGIN
 SELECT * INTO f FROM public.order_accounting_facts WHERE order_id=p_order_id;IF NOT FOUND THEN RETURN NULL;END IF;SELECT * INTO o FROM public.orders WHERE id=p_order_id;
 SELECT COUNT(*)::bigint,COUNT(*) FILTER(WHERE cost_status NOT IN ('exact','verified_zero') OR actual_cost IS NULL)::bigint,COALESCE(SUM(actual_cost) FILTER(WHERE cost_status IN ('exact','verified_zero') AND actual_cost IS NOT NULL),0) INTO v_events,v_bad,v_cost FROM public.order_fulfillment_events WHERE order_id=p_order_id AND event_type='original' AND workflow_state='confirmed';
 IF v_events=0 THEN v_cost:=COALESCE(o.box_cost,0);IF v_cost<=0 THEN RETURN NULL;END IF;ELSIF v_bad>0 THEN RETURN NULL;END IF;
 SELECT id INTO v_entry_id FROM public.journal_entries WHERE source_type='order' AND source_id=p_order_id AND event_kind='fulfillment_recognition';IF FOUND THEN IF (SELECT total_debit FROM public.journal_entries WHERE id=v_entry_id)<>v_cost THEN RAISE EXCEPTION 'FULFILLMENT_JOURNAL_IMMUTABLE: cost changed for order %; reverse and repost',p_order_id;END IF;RETURN v_entry_id;END IF;
 INSERT INTO public.journal_entries(entry_date,period_key,source_type,source_id,event_kind,description,total_debit,total_credit,evidence) VALUES(f.recognized_at,f.period_key,'order',p_order_id,'fulfillment_recognition','إثبات كلفة مواد تجهيز وتغليف AQUAVO',v_cost,v_cost,jsonb_build_object('order_accounting_fact_id',f.id,'source',CASE WHEN v_events>0 THEN 'confirmed_fulfillment_event' ELSE 'legacy_box_cost' END)) RETURNING id INTO v_entry_id;
 INSERT INTO public.journal_lines(entry_id,line_number,account_code,debit,memo) VALUES(v_entry_id,1,'5100',v_cost,'مواد تجهيز وتغليف الطلب');
 INSERT INTO public.journal_lines(entry_id,line_number,account_code,credit,memo) VALUES(v_entry_id,2,'1210',v_cost,'استهلاك مخزون مواد التجهيز');
 PERFORM public.validate_journal_entry(v_entry_id);RETURN v_entry_id;
END $$;

CREATE OR REPLACE FUNCTION public.post_fulfillment_after_confirmation() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v_original text;v_reversal text;v_total numeric;v_period text;
BEGIN
 IF NEW.event_type='original' AND NEW.workflow_state='confirmed' AND (TG_OP='INSERT' OR OLD.workflow_state IS DISTINCT FROM 'confirmed' OR OLD.actual_cost IS DISTINCT FROM NEW.actual_cost OR OLD.cost_status IS DISTINCT FROM NEW.cost_status) THEN PERFORM public.post_order_fulfillment_journal(NEW.order_id);END IF;
 IF TG_OP='UPDATE' AND OLD.event_type='original' AND OLD.workflow_state='confirmed' AND NEW.workflow_state='reversed' THEN
  SELECT id,total_debit,period_key INTO v_original,v_total,v_period FROM public.journal_entries WHERE source_type='order' AND source_id=NEW.order_id AND event_kind='fulfillment_recognition';
  IF v_original IS NOT NULL THEN INSERT INTO public.journal_entries(entry_date,period_key,source_type,source_id,event_kind,description,total_debit,total_credit,reversal_of_entry_id,evidence,created_by) VALUES(clock_timestamp(),to_char(clock_timestamp() AT TIME ZONE 'Asia/Baghdad','YYYY-MM'),'order_fulfillment_event',NEW.id,'fulfillment_reversal','عكس كلفة تجهيز طلب: '||COALESCE(NEW.adjustment_reason,'تم عكس حدث التجهيز'),v_total,v_total,v_original,jsonb_build_object('order_id',NEW.order_id,'original_period',v_period),NEW.recorded_by) ON CONFLICT(source_type,source_id,event_kind) DO NOTHING RETURNING id INTO v_reversal;IF v_reversal IS NOT NULL THEN INSERT INTO public.journal_lines(entry_id,line_number,account_code,debit,credit,memo,dimensions) SELECT v_reversal,line_number,account_code,credit,debit,'عكس: '||COALESCE(memo,''),dimensions FROM public.journal_lines WHERE entry_id=v_original ORDER BY line_number;PERFORM public.validate_journal_entry(v_reversal);END IF;END IF;
 END IF;RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS order_fulfillment_post_journal ON public.order_fulfillment_events;
CREATE TRIGGER order_fulfillment_post_journal AFTER INSERT OR UPDATE OF workflow_state,actual_cost,cost_status ON public.order_fulfillment_events FOR EACH ROW EXECUTE FUNCTION public.post_fulfillment_after_confirmation();

-- Seven active non-variant products had storefront stock but no canonical movement.
-- Keep them sellable, but label the cutover provisional and block close until a
-- physical stocktake/evidence resolves the review flags.
WITH main AS(SELECT id FROM public.inventory_locations WHERE code='MAIN' AND is_active=true LIMIT 1),missing AS(
 SELECT p.id product_id,p.stock,p.cost_price FROM public.products p LEFT JOIN public.inventory_movements im ON im.product_id=p.id AND im.variant_id IS NULL AND im.location_id=(SELECT id FROM main) WHERE p.deleted_at IS NULL AND COALESCE(p.has_variants,false)=false AND p.stock>0 GROUP BY p.id,p.stock,p.cost_price HAVING COALESCE(SUM(im.quantity_delta),0)=0)
INSERT INTO public.inventory_movements(product_id,variant_id,location_id,quantity_delta,movement_type,source_type,source_id,idempotency_key,unit_cost,currency,happened_at,created_by,metadata)
SELECT product_id,NULL,(SELECT id FROM main),stock,'opening_balance','accounting_cutover_provisional','aquavo-2026-08-01','cutover:2026-08-01:'||product_id,CASE WHEN cost_price>0 THEN cost_price END,'IQD','2026-08-01 00:00:00 Asia/Baghdad'::timestamptz,'migration_0054',jsonb_build_object('confidence','provisional','requires_owner_stocktake',true) FROM missing ON CONFLICT(idempotency_key) DO NOTHING;

INSERT INTO public.accounting_review_flags(category,severity,entity_type,entity_id,title,description,detected_value_json,suggested_value_json,status)
SELECT 'stock','high','product',im.product_id,'رصيد افتتاحي مؤقت يحتاج جرد فعلي','أُنشئ رصيد 1 آب من products.stock لأن دفتر الحركات كان صفراً. يبقى الإغلاق ممنوعاً حتى اعتماد الجرد الفعلي.',jsonb_build_object('quantity',im.quantity_delta,'unit_cost',im.unit_cost,'movement_id',im.id),jsonb_build_object('action','verify_physical_stocktake'),'open' FROM public.inventory_movements im WHERE im.source_type='accounting_cutover_provisional' AND im.source_id='aquavo-2026-08-01' AND NOT EXISTS(SELECT 1 FROM public.accounting_review_flags f WHERE f.category='stock' AND f.entity_id=im.product_id AND f.status='open' AND f.title='رصيد افتتاحي مؤقت يحتاج جرد فعلي');

INSERT INTO public.accounting_review_flags(category,severity,entity_type,entity_id,title,description,detected_value_json,suggested_value_json,status)
SELECT 'product_cost','high','accounting_cutover','aquavo-2026-08-01','كلف تغليف/إضافات المنتجات غير محسومة','الصفر غير المؤكد لا يعامل ككلفة صفر. أدخل الكلفة أو اعتمد verified_zero قبل إغلاق آب.',jsonb_build_object('affected_products',COUNT(*)),jsonb_build_object('action','resolve_product_cost_components'),'open' FROM public.products p WHERE p.deleted_at IS NULL AND (COALESCE(p.packaging_cost_resolution,'unresolved')='unresolved' OR COALESCE(p.insert_cost_resolution,'unresolved')='unresolved') HAVING COUNT(*)>0 AND NOT EXISTS(SELECT 1 FROM public.accounting_review_flags f WHERE f.category='product_cost' AND f.entity_id='aquavo-2026-08-01' AND f.status='open');

INSERT INTO public.opening_inventory_snapshot(cutover_id,product_id,variant_id,location_id,quantity,unit_cost,cost_status,total_cost,as_of,evidence)
SELECT 'aquavo-2026-08-01',b.product_id,b.variant_id,b.location_id,b.quantity,CASE WHEN p.cost_price>0 THEN p.cost_price END,CASE WHEN EXISTS(SELECT 1 FROM public.inventory_movements x WHERE x.product_id=b.product_id AND x.variant_id IS NOT DISTINCT FROM b.variant_id AND x.location_id=b.location_id AND x.source_type='accounting_cutover_provisional') THEN 'provisional' WHEN p.cost_price>0 THEN 'known' ELSE 'unknown' END,CASE WHEN p.cost_price>0 THEN p.cost_price*b.quantity END,'2026-08-01 00:00:00 Asia/Baghdad'::timestamptz,jsonb_build_object('source','canonical inventory ledger after cutover reconciliation') FROM(SELECT product_id,variant_id,location_id,SUM(quantity_delta)::integer quantity FROM public.inventory_movements WHERE happened_at<='2026-08-01 00:00:00 Asia/Baghdad'::timestamptz GROUP BY product_id,variant_id,location_id)b JOIN public.products p ON p.id=b.product_id WHERE b.quantity>=0 ON CONFLICT(cutover_id,product_id,variant_id,location_id) DO NOTHING;

ALTER TABLE public.accounting_period_closes ADD COLUMN IF NOT EXISTS delivery_subsidy_total numeric NOT NULL DEFAULT 0;
ALTER TABLE public.accounting_period_closes ADD COLUMN IF NOT EXISTS delivery_surplus_total numeric NOT NULL DEFAULT 0;
ALTER TABLE public.accounting_period_closes ADD COLUMN IF NOT EXISTS fulfillment_cost_total numeric NOT NULL DEFAULT 0;
ALTER TABLE public.accounting_period_closes ADD COLUMN IF NOT EXISTS readiness_json jsonb NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE public.accounting_period_closes ADD COLUMN IF NOT EXISTS close_type text NOT NULL DEFAULT 'administrative';
DO $$ BEGIN ALTER TABLE public.accounting_period_closes ADD CONSTRAINT accounting_period_closes_period_key_unique UNIQUE(period_key);EXCEPTION WHEN duplicate_object THEN NULL;END $$;
DO $$ BEGIN ALTER TABLE public.accounting_period_closes ADD CONSTRAINT accounting_period_closes_close_type_chk CHECK(close_type IN ('administrative','tax_final')) NOT VALID;EXCEPTION WHEN duplicate_object THEN NULL;END $$;

CREATE OR REPLACE VIEW public.v_order_accounting AS SELECT f.order_id,o.order_number,o.source,o.status,o.payment_status,o.cod_received,f.recognized_at,f.period_key,f.gross_collected,f.customer_delivery_fee,f.carrier_fee,f.product_revenue,f.merchant_net,f.delivery_subsidy,f.delivery_surplus,f.cash_custody,f.cogs_amount,f.cost_status,CASE WHEN f.cogs_amount IS NULL THEN NULL ELSE f.product_revenue-f.cogs_amount-f.delivery_subsidy END contribution_profit,CASE WHEN s.id IS NULL THEN 'unsettled' ELSE s.status END settlement_status,s.settlement_id,f.policy_version FROM public.order_accounting_facts f JOIN public.orders o ON o.id=f.order_id LEFT JOIN public.order_accounting_settlements s ON s.order_fact_id=f.id;

CREATE OR REPLACE VIEW public.v_accounting_period_readiness AS
WITH months AS(SELECT to_char(gs,'YYYY-MM') period_key FROM public.accounting_cutovers c,LATERAL generate_series(date_trunc('month',c.cutover_at AT TIME ZONE 'Asia/Baghdad'),date_trunc('month',clock_timestamp() AT TIME ZONE 'Asia/Baghdad'),interval '1 month')gs WHERE c.status='active'),main AS(SELECT id FROM public.inventory_locations WHERE code='MAIN' AND is_active=true LIMIT 1),inventory_check AS(SELECT COUNT(*)::bigint mismatches FROM public.products p LEFT JOIN(SELECT product_id,variant_id,SUM(quantity_delta)::integer qty FROM public.inventory_movements WHERE location_id=(SELECT id FROM main) GROUP BY product_id,variant_id)x ON x.product_id=p.id AND x.variant_id IS NULL WHERE p.deleted_at IS NULL AND COALESCE(p.has_variants,false)=false AND COALESCE(p.stock,0)<>COALESCE(x.qty,0)),flags AS(SELECT COUNT(*)::bigint n FROM public.accounting_review_flags WHERE status='open')
SELECT m.period_key,
 COALESCE((SELECT COUNT(*) FROM public.order_accounting_facts f WHERE f.period_key=m.period_key),0)::bigint realized_orders,
 COALESCE((SELECT COUNT(*) FROM public.order_accounting_facts f WHERE f.period_key=m.period_key AND (f.cost_status NOT IN ('exact','verified_zero') OR f.cogs_amount IS NULL)),0)::bigint incomplete_cost_orders,
 COALESCE((SELECT COUNT(*) FROM public.order_accounting_facts f JOIN public.orders o ON o.id=f.order_id WHERE f.period_key=m.period_key AND NOT EXISTS(SELECT 1 FROM public.order_fulfillment_events e WHERE e.order_id=f.order_id AND e.event_type='original' AND e.workflow_state='confirmed') AND COALESCE(o.box_cost,0)<=0),0)::bigint missing_fulfillment_orders,
 COALESCE((SELECT COUNT(*) FROM public.order_accounting_facts f WHERE f.period_key=m.period_key AND EXISTS(SELECT 1 FROM public.order_fulfillment_events e WHERE e.order_id=f.order_id AND e.event_type='original' AND e.workflow_state='confirmed' AND (e.cost_status NOT IN ('exact','verified_zero') OR e.actual_cost IS NULL))),0)::bigint incomplete_fulfillment_orders,
 COALESCE((SELECT COUNT(*) FROM public.order_accounting_facts f WHERE f.period_key=m.period_key AND NOT EXISTS(SELECT 1 FROM public.payment_events p WHERE p.id=f.payment_event_id AND p.status='completed' AND p.amount=f.gross_collected)),0)::bigint payment_evidence_errors,
 COALESCE((SELECT COUNT(*) FROM public.order_accounting_facts f WHERE f.period_key=m.period_key AND f.cash_custody='carrier' AND NOT EXISTS(SELECT 1 FROM public.order_accounting_settlements s WHERE s.order_fact_id=f.id AND s.status='matched')),0)::bigint unsettled_carrier_orders,
 COALESCE((SELECT COUNT(*) FROM public.order_accounting_facts f WHERE f.period_key=m.period_key AND f.delivery_surplus>0),0)::bigint delivery_surplus_exceptions,
 COALESCE((SELECT COUNT(*) FROM public.order_return_events r WHERE to_char(r.updated_at AT TIME ZONE 'UTC' AT TIME ZONE 'Asia/Baghdad','YYYY-MM')=m.period_key AND r.status='recorded'),0)::bigint unverified_returns,
 COALESCE((SELECT COUNT(*) FROM public.expenses e WHERE to_char(COALESCE(e.expense_occurred_at,e.expense_date AT TIME ZONE 'Asia/Baghdad') AT TIME ZONE 'Asia/Baghdad','YYYY-MM')=m.period_key AND e.deleted_at IS NULL AND e.accounting_status NOT IN ('verified','rejected')),0)::bigint undocumented_expenses,
 (SELECT mismatches FROM inventory_check) inventory_mismatches,(SELECT n FROM flags) open_review_flags,
 COALESCE((SELECT SUM(l.debit)-SUM(l.credit) FROM public.journal_entries j JOIN public.journal_lines l ON l.entry_id=j.id WHERE j.period_key=m.period_key),0) journal_difference,
 COALESCE((SELECT SUM(product_revenue) FROM public.order_accounting_facts f WHERE f.period_key=m.period_key),0) product_revenue,
 COALESCE((SELECT SUM(merchant_net) FROM public.order_accounting_facts f WHERE f.period_key=m.period_key),0) merchant_net,
 COALESCE((SELECT SUM(delivery_subsidy) FROM public.order_accounting_facts f WHERE f.period_key=m.period_key),0) delivery_subsidy,
 COALESCE((SELECT SUM(delivery_surplus) FROM public.order_accounting_facts f WHERE f.period_key=m.period_key),0) delivery_surplus,
 COALESCE((SELECT SUM(cogs_amount) FROM public.order_accounting_facts f WHERE f.period_key=m.period_key),0) cogs,
 COALESCE((SELECT SUM(CASE WHEN EXISTS(SELECT 1 FROM public.order_fulfillment_events e WHERE e.order_id=f.order_id AND e.event_type='original' AND e.workflow_state='confirmed') THEN (SELECT SUM(e.actual_cost) FROM public.order_fulfillment_events e WHERE e.order_id=f.order_id AND e.event_type='original' AND e.workflow_state='confirmed') ELSE o.box_cost END) FROM public.order_accounting_facts f JOIN public.orders o ON o.id=f.order_id WHERE f.period_key=m.period_key),0) fulfillment_cost,
 COALESCE((SELECT SUM(refund_amount) FROM public.order_return_events r WHERE r.status='verified' AND to_char(r.updated_at AT TIME ZONE 'UTC' AT TIME ZONE 'Asia/Baghdad','YYYY-MM')=m.period_key),0) sales_returns,
 COALESCE((SELECT SUM(COALESCE(delivery_cost_loss,0)+COALESCE(return_shipping_cost,0)+COALESCE(packaging_loss,0)+COALESCE(product_write_off_amount,0)+CASE WHEN restocked=true THEN 0 ELSE COALESCE(cogs_loss,0) END) FROM public.order_return_events r WHERE r.status='verified' AND to_char(r.updated_at AT TIME ZONE 'UTC' AT TIME ZONE 'Asia/Baghdad','YYYY-MM')=m.period_key),0) actual_return_loss,
 COALESCE((SELECT SUM(amount) FROM public.expenses e WHERE e.deleted_at IS NULL AND e.accounting_status='verified' AND to_char(COALESCE(e.expense_occurred_at,e.expense_date AT TIME ZONE 'Asia/Baghdad') AT TIME ZONE 'Asia/Baghdad','YYYY-MM')=m.period_key),0) verified_expenses
FROM months m;

CREATE OR REPLACE FUNCTION public.guard_accounting_period_tax_finalization() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE r public.v_accounting_period_readiness%ROWTYPE;p public.tax_profiles%ROWTYPE;period_end date;
BEGIN
 IF lower(COALESCE(NEW.status,''))='reopened' THEN RETURN NEW;END IF;SELECT * INTO r FROM public.v_accounting_period_readiness WHERE period_key=NEW.period_key;period_end:=(to_date(NEW.period_key||'-01','YYYY-MM-DD')+interval '1 month')::date;
 IF lower(NEW.status) IN('closed','administrative_closed','locked') THEN IF (clock_timestamp() AT TIME ZONE 'Asia/Baghdad')::date<period_end THEN RAISE EXCEPTION 'ADMIN_CLOSE_BLOCKED: period % has not ended',NEW.period_key;END IF;IF r.incomplete_cost_orders>0 OR r.missing_fulfillment_orders>0 OR r.incomplete_fulfillment_orders>0 OR r.payment_evidence_errors>0 OR r.unverified_returns>0 OR r.undocumented_expenses>0 OR r.inventory_mismatches>0 OR r.open_review_flags>0 OR r.unsettled_carrier_orders>0 OR r.delivery_surplus_exceptions>0 OR r.journal_difference<>0 THEN RAISE EXCEPTION 'ADMIN_CLOSE_BLOCKED: readiness failed for %',NEW.period_key;END IF;NEW.close_type:='administrative';END IF;
 IF lower(NEW.status) IN('final','finalized','approved','tax_final') THEN SELECT * INTO p FROM public.tax_profiles WHERE id='al-manba-aquavo';IF TG_OP='INSERT' OR lower(COALESCE(OLD.status,'')) NOT IN('closed','administrative_closed','locked') THEN RAISE EXCEPTION 'TAX_FINALIZATION_BLOCKED: administrative close required';END IF;IF p.status<>'approved' OR p.taxpayer_number IS NULL OR p.tax_branch IS NULL OR p.registered_address IS NULL OR p.accountant_license_number IS NULL OR p.accountant_approved_at IS NULL OR p.approval_evidence_id IS NULL THEN RAISE EXCEPTION 'TAX_FINALIZATION_BLOCKED: tax profile/accountant approval incomplete';END IF;NEW.close_type:='tax_final';END IF;
 NEW.revenue:=r.product_revenue;NEW.cogs:=r.cogs;NEW.gross_profit:=r.product_revenue-r.cogs;NEW.expenses_total:=r.verified_expenses;NEW.sales_return_deduction:=r.sales_returns;NEW.actual_return_loss:=r.actual_return_loss;NEW.delivery_subsidy_total:=r.delivery_subsidy;NEW.delivery_surplus_total:=r.delivery_surplus;NEW.fulfillment_cost_total:=r.fulfillment_cost;NEW.final_net_profit:=r.product_revenue-r.cogs-r.fulfillment_cost-r.delivery_subsidy-r.sales_returns-r.actual_return_loss-r.verified_expenses;NEW.delivered_orders:=r.realized_orders;NEW.readiness_json:=to_jsonb(r);NEW.snapshot_json:=COALESCE(NEW.snapshot_json,'{}'::jsonb)||jsonb_build_object('policy_version','v2_gross_includes_delivery_carrier_keeps_fee','timezone','Asia/Baghdad','cutover','2026-08-01','readiness',to_jsonb(r));RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_guard_accounting_period_tax_finalization ON public.accounting_period_closes;
CREATE TRIGGER trg_guard_accounting_period_tax_finalization BEFORE INSERT OR UPDATE OF status,period_start,period_end ON public.accounting_period_closes FOR EACH ROW EXECUTE FUNCTION public.guard_accounting_period_tax_finalization();

INSERT INTO public.schema_migrations(version,checksum,notes) VALUES('0054_accounting_fulfillment_readiness','d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4','Fulfillment journals, provisional opening inventory, review flags, readiness views and administrative/tax close gates') ON CONFLICT(version) DO NOTHING;
COMMIT;
