-- PREPARED — NOT APPLIED. Requires Jaafar's approval before it touches Neon production.
--
-- PURPOSE
-- -------
-- Give an order a durable link back to the session, and therefore to the ad click, that produced it.
--
-- Growth OS can measure spend and delivery but not outcome: attribution coverage is 5% and capi.mjs
-- returns NO_JOIN_KEY. The reason is not that fbclid is missing — that claim was investigated and
-- retracted; posthog-js captures fbclid, gclid and the UTM set automatically on 599–913 pageviews a
-- month. The reason is that none of it ever reaches the `orders` row, so there is nothing to join ON.
--
-- WHAT THIS DELIBERATELY IS NOT
-- -----------------------------
-- It is not a timestamp join. "An ad click happened four minutes before an order" is a coincidence with
-- a plausible story attached, and at AQUAVO's volume the coincidence rate is high enough to manufacture
-- any conclusion you like. `aq_sid` is a stable random identifier minted in the browser and carried to
-- the order; either it is present and the join is real, or it is absent and the order is honestly
-- unattributed. There is no middle state and no inference.
--
-- PRIVACY
-- -------
-- Every column below is campaign metadata or an opaque random id. None of it identifies a person, and
-- `aq_sid` is generated by crypto.randomUUID() with no derivation from anything about the customer.
-- The marketing-safe layer's PII rules are unaffected: nothing here is a phone, email, name or address.
--
-- COMPATIBILITY
-- -------------
-- Every column is NULLABLE with no default. Orders created before this lands stay NULL, and NULL means
-- "we do not know" — never "direct", never "organic". That distinction is the whole point: an order
-- with no attribution must not be silently credited to a channel. The server write path treats every
-- field as optional, so a client that has not been updated, a customer with localStorage disabled, and
-- an order placed by phone all continue to work unchanged.
--
-- ROLLBACK
-- --------
--   ALTER TABLE orders
--     DROP COLUMN IF EXISTS aq_sid,
--     DROP COLUMN IF EXISTS attribution_utm_source,
--     DROP COLUMN IF EXISTS attribution_utm_medium,
--     DROP COLUMN IF EXISTS attribution_utm_campaign,
--     DROP COLUMN IF EXISTS attribution_fbclid,
--     DROP COLUMN IF EXISTS aq_campaign_id,
--     DROP COLUMN IF EXISTS aq_adset_id,
--     DROP COLUMN IF EXISTS aq_ad_id,
--     DROP COLUMN IF EXISTS aq_creative_id,
--     DROP COLUMN IF EXISTS aq_concept_id,
--     DROP COLUMN IF EXISTS aq_hypothesis_id,
--     DROP COLUMN IF EXISTS aq_experiment_id,
--     DROP COLUMN IF EXISTS attribution_captured_at;
--   DROP INDEX IF EXISTS idx_orders_aq_sid;
--
-- Additive and nullable, so the rollback is a pure drop: no data is rewritten, and no existing query
-- changes meaning while the columns exist unused.

BEGIN;

ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS aq_sid                   text,
  ADD COLUMN IF NOT EXISTS attribution_utm_source   text,
  ADD COLUMN IF NOT EXISTS attribution_utm_medium   text,
  ADD COLUMN IF NOT EXISTS attribution_utm_campaign text,
  ADD COLUMN IF NOT EXISTS attribution_fbclid       text,
  ADD COLUMN IF NOT EXISTS aq_campaign_id           text,
  ADD COLUMN IF NOT EXISTS aq_adset_id              text,
  ADD COLUMN IF NOT EXISTS aq_ad_id                 text,
  ADD COLUMN IF NOT EXISTS aq_creative_id           text,
  ADD COLUMN IF NOT EXISTS aq_concept_id            text,
  ADD COLUMN IF NOT EXISTS aq_hypothesis_id         text,
  ADD COLUMN IF NOT EXISTS aq_experiment_id         text,
  ADD COLUMN IF NOT EXISTS attribution_captured_at  timestamp;

COMMENT ON COLUMN orders.aq_sid IS
  'Opaque browser-scoped acquisition id (crypto.randomUUID), set at first pageview and carried to the order. The ONLY sanctioned join key between a session and an order. NULL means unattributed — never assume direct.';
COMMENT ON COLUMN orders.attribution_captured_at IS
  'When the campaign parameters were observed in the browser, which is NOT when the order was placed. Kept separate so the lag between click and purchase is measurable rather than assumed.';

-- Partial: only attributed orders are worth indexing, and most historical rows are NULL.
CREATE INDEX IF NOT EXISTS idx_orders_aq_sid ON orders (aq_sid) WHERE aq_sid IS NOT NULL;

COMMIT;

-- VERIFICATION (run after applying; all three must hold)
--
--   -- 1. every column exists and is nullable
--   SELECT column_name, is_nullable, column_default
--     FROM information_schema.columns
--    WHERE table_name = 'orders' AND (column_name = 'aq_sid' OR column_name LIKE 'aq\_%' OR column_name LIKE 'attribution\_%')
--    ORDER BY column_name;
--   -- expect: 13 rows, is_nullable = YES, column_default = NULL for all
--
--   -- 2. no existing order was modified
--   SELECT count(*) AS total, count(aq_sid) AS attributed FROM orders;
--   -- expect: attributed = 0 immediately after the migration
--
--   -- 3. the index exists and is partial
--   SELECT indexdef FROM pg_indexes WHERE indexname = 'idx_orders_aq_sid';
--   -- expect: ... WHERE (aq_sid IS NOT NULL)
