import { beforeAll, describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { PGlite } from "@electric-sql/pglite";

const root = process.cwd();
const migration = readFileSync(join(root, "migrations/0062_accounting_automation_opening_balances.sql"), "utf8");

const BASE = String.raw`
CREATE TABLE accounting_monthly_positions(
  id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  period_key text NOT NULL,
  position_type text NOT NULL,
  amount numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'confirmed'
);
INSERT INTO accounting_monthly_positions(period_key,position_type,amount,status) VALUES
  ('2026-08','cash',670000,'confirmed'),
  ('2026-08','carrier_receivable',153750,'confirmed');

CREATE TABLE opening_inventory_snapshot(
  id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  cutover_id text NOT NULL,
  cost_status text NOT NULL,
  total_cost numeric
);
INSERT INTO opening_inventory_snapshot(cutover_id,cost_status,total_cost)
VALUES('aquavo-2026-08-01','known',2256781);

CREATE TABLE chart_of_accounts(
  code text PRIMARY KEY,
  name_ar text NOT NULL,
  account_type text NOT NULL,
  normal_side text NOT NULL,
  active boolean NOT NULL DEFAULT true
);
INSERT INTO chart_of_accounts(code,name_ar,account_type,normal_side) VALUES
  ('1000','الصندوق','asset','debit'),
  ('1010','البنك','asset','debit'),
  ('1100','ذمم COD','asset','debit'),
  ('1200','مخزون المنتجات','asset','debit'),
  ('3100','رأس مال المالك','equity','credit'),
  ('4100','مردودات المبيعات','contra_revenue','debit'),
  ('4200','خسائر المرتجعات','expense','debit');

CREATE TABLE journal_entries(
  id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  entry_number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  entry_date timestamptz NOT NULL,
  period_key text NOT NULL,
  source_type text NOT NULL,
  source_id text NOT NULL,
  event_kind text NOT NULL,
  description text NOT NULL,
  status text NOT NULL DEFAULT 'posted',
  currency text NOT NULL DEFAULT 'IQD',
  total_debit numeric NOT NULL,
  total_credit numeric NOT NULL,
  reversal_of_entry_id text,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(source_type,source_id,event_kind)
);
CREATE TABLE journal_lines(
  id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  entry_id text NOT NULL REFERENCES journal_entries(id),
  line_number integer NOT NULL,
  account_code text NOT NULL REFERENCES chart_of_accounts(code),
  debit numeric NOT NULL DEFAULT 0,
  credit numeric NOT NULL DEFAULT 0,
  memo text,
  dimensions jsonb NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE(entry_id,line_number)
);
CREATE OR REPLACE FUNCTION validate_journal_entry(p_entry_id text)
RETURNS void LANGUAGE plpgsql AS $validate$
DECLARE v_header record;v_debit numeric;v_credit numeric;
BEGIN
  SELECT total_debit,total_credit INTO v_header FROM journal_entries WHERE id=p_entry_id;
  SELECT COALESCE(SUM(debit),0),COALESCE(SUM(credit),0) INTO v_debit,v_credit FROM journal_lines WHERE entry_id=p_entry_id;
  IF v_debit<>v_credit OR v_debit<>v_header.total_debit OR v_credit<>v_header.total_credit THEN
    RAISE EXCEPTION 'unbalanced';
  END IF;
END $validate$;

CREATE TABLE accounting_period_closes(
  id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  period_key text NOT NULL UNIQUE,
  period_start timestamp NOT NULL,
  period_end timestamp NOT NULL,
  status text NOT NULL DEFAULT 'closed',
  closed_by text,
  closed_by_name text,
  snapshot_json jsonb,
  closed_at timestamp NOT NULL DEFAULT now(),
  reopened_by text,
  reopened_reason text,
  reopened_at timestamp
);
CREATE TABLE accounting_cutovers(
  id text PRIMARY KEY,
  cutover_at timestamptz NOT NULL,
  status text NOT NULL
);
INSERT INTO accounting_cutovers VALUES('aquavo-2026-08-01','2026-08-01 00:00:00+03','active');

CREATE TABLE readiness_stub(
  period_key text PRIMARY KEY,
  realized_orders bigint NOT NULL DEFAULT 0,
  incomplete_cost_orders bigint NOT NULL DEFAULT 0,
  missing_fulfillment_orders bigint NOT NULL DEFAULT 0,
  incomplete_fulfillment_orders bigint NOT NULL DEFAULT 0,
  payment_evidence_errors bigint NOT NULL DEFAULT 0,
  unsettled_carrier_orders bigint NOT NULL DEFAULT 0,
  delivery_surplus_exceptions bigint NOT NULL DEFAULT 0,
  unverified_returns bigint NOT NULL DEFAULT 0,
  undocumented_expenses bigint NOT NULL DEFAULT 0,
  inventory_mismatches bigint NOT NULL DEFAULT 0,
  open_review_flags bigint NOT NULL DEFAULT 0,
  journal_difference numeric NOT NULL DEFAULT 0,
  product_revenue numeric NOT NULL DEFAULT 0,
  merchant_net numeric NOT NULL DEFAULT 0,
  delivery_subsidy numeric NOT NULL DEFAULT 0,
  delivery_surplus numeric NOT NULL DEFAULT 0,
  cogs numeric NOT NULL DEFAULT 0,
  fulfillment_cost numeric NOT NULL DEFAULT 0,
  sales_returns numeric NOT NULL DEFAULT 0,
  actual_return_loss numeric NOT NULL DEFAULT 0,
  verified_expenses numeric NOT NULL DEFAULT 0
);
INSERT INTO readiness_stub(period_key) VALUES('2026-08');
CREATE VIEW v_accounting_period_readiness AS SELECT * FROM readiness_stub;

CREATE TABLE order_accounting_facts(
  id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  order_id text NOT NULL,
  cash_custody text NOT NULL DEFAULT 'carrier',
  period_key text,
  recognized_at timestamptz,
  gross_collected numeric,
  carrier_fee numeric,
  merchant_net numeric
);
CREATE TABLE order_accounting_settlements(
  id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  order_fact_id text,
  status text
);
CREATE OR REPLACE FUNCTION aquavo_active_cutover()
RETURNS timestamptz LANGUAGE sql STABLE AS $cutover$
  SELECT '2026-08-01 00:00:00+03'::timestamptz
$cutover$;

CREATE TABLE order_return_events(
  id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  order_id text NOT NULL,
  type text NOT NULL,
  reason text,
  refund_amount numeric NOT NULL DEFAULT 0,
  delivery_cost_loss numeric NOT NULL DEFAULT 0,
  return_shipping_cost numeric NOT NULL DEFAULT 0,
  packaging_loss numeric NOT NULL DEFAULT 0,
  product_write_off_amount numeric NOT NULL DEFAULT 0,
  cogs_loss numeric NOT NULL DEFAULT 0,
  restocked boolean NOT NULL DEFAULT false,
  restocked_at timestamp,
  affected_items jsonb,
  status text NOT NULL DEFAULT 'recorded',
  note text,
  created_by text,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now(),
  packaging_loss_source text NOT NULL DEFAULT 'manual'
);
CREATE OR REPLACE FUNCTION post_verified_return_journal()
RETURNS trigger LANGUAGE plpgsql AS $old_return$ BEGIN RETURN NEW; END $old_return$;
CREATE TRIGGER order_return_post_journal
AFTER UPDATE OF status ON order_return_events
FOR EACH ROW EXECUTE FUNCTION post_verified_return_journal();

CREATE TABLE settings(key text PRIMARY KEY,value text);
INSERT INTO settings VALUES('inventory_ledger_mode','enforce');
CREATE TABLE inventory_locations(id text PRIMARY KEY,code text,is_active boolean);
INSERT INTO inventory_locations VALUES('main','MAIN',true);
CREATE TABLE orders(id text PRIMARY KEY,status text NOT NULL);
CREATE TABLE order_items_relational(
  id text PRIMARY KEY,
  order_id text NOT NULL,
  product_id text NOT NULL,
  quantity integer NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE TABLE inventory_movements(
  id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  product_id text NOT NULL,
  variant_id text,
  location_id text NOT NULL,
  quantity_delta integer NOT NULL,
  movement_type text NOT NULL,
  source_type text NOT NULL,
  source_id text,
  idempotency_key text NOT NULL UNIQUE,
  currency text NOT NULL DEFAULT 'IQD',
  happened_at timestamptz NOT NULL,
  created_by text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE OR REPLACE FUNCTION reverse_order_inventory_on_terminal_status()
RETURNS trigger LANGUAGE plpgsql AS $old_inventory$ BEGIN RETURN NEW; END $old_inventory$;
CREATE TRIGGER orders_reverse_inventory_terminal
AFTER UPDATE OF status ON orders
FOR EACH ROW EXECUTE FUNCTION reverse_order_inventory_on_terminal_status();

CREATE TABLE schema_migrations(
  version text PRIMARY KEY,
  checksum text NOT NULL,
  notes text,
  applied_at timestamptz NOT NULL DEFAULT now(),
  rolled_back_at timestamptz
);
`;

describe("0062 accounting automation migration execution (PGlite PostgreSQL)", () => {
  let db: PGlite;

  beforeAll(async () => {
    db = new PGlite();
    await db.exec(BASE);
    await db.exec(migration);
  }, 60_000);

  it("posts the exact confirmed opening entry", async () => {
    const entry = await db.query<{ total_debit: string; total_credit: string }>(`
      SELECT total_debit::text,total_credit::text
      FROM journal_entries
      WHERE source_type='accounting_cutover' AND event_kind='opening_balances'
    `);
    expect(entry.rows).toHaveLength(1);
    expect(Number(entry.rows[0].total_debit)).toBe(3_080_531);
    expect(Number(entry.rows[0].total_credit)).toBe(3_080_531);

    const balances = await db.query<{ code: string; balance: string }>(`
      SELECT code,balance::text FROM v_accounting_live_balances
      WHERE code IN ('1000','1100','1200','3100') ORDER BY code
    `);
    expect(Object.fromEntries(balances.rows.map((row) => [row.code, Number(row.balance)]))).toEqual({
      "1000": 670_000,
      "1100": 153_750,
      "1200": 2_256_781,
      "3100": 3_080_531,
    });
  });

  it("verifies a zero-cash rejected return without inventing a delivered sale", async () => {
    await db.exec(`
      INSERT INTO order_return_events(id,order_id,type,reason,status,restocked,packaging_loss_source,created_at,updated_at)
      VALUES('ret-auto','order-rejected','rejected_delivery','AUTO_ORDER_STATUS_REJECTED','recorded',false,'fulfillment_snapshot',now(),now());
      UPDATE order_return_events SET status='verified',restocked=true,restocked_at=now(),updated_at=now()
      WHERE id='ret-auto';
    `);
    const row = await db.query<{ status: string; restocked: boolean }>(`SELECT status,restocked FROM order_return_events WHERE id='ret-auto'`);
    expect(row.rows[0]).toEqual({ status: "verified", restocked: true });
    const journals = await db.query<{ n: number }>(`SELECT COUNT(*)::int AS n FROM journal_entries WHERE source_type='return_event' AND source_id='ret-auto'`);
    expect(journals.rows[0].n).toBe(0);
  });

  it("does not restore stock at rejection and restores exactly once at receipt", async () => {
    await db.exec(`
      INSERT INTO orders VALUES('ord-1','shipped');
      INSERT INTO order_items_relational(id,order_id,product_id,quantity) VALUES('oi-1','ord-1','p-1',2);
      INSERT INTO inventory_movements(product_id,location_id,quantity_delta,movement_type,source_type,source_id,idempotency_key,happened_at)
      VALUES('p-1','main',-2,'sale','order_item','ord-1','order_item:oi-1',now());
      UPDATE orders SET status='rejected' WHERE id='ord-1';
    `);
    let result = await db.query<{ n: number }>(`SELECT COUNT(*)::int AS n FROM inventory_movements WHERE source_type='order_status_reversal'`);
    expect(result.rows[0].n).toBe(0);

    await db.exec(`UPDATE orders SET status='returned' WHERE id='ord-1'`);
    result = await db.query<{ n: number; qty: number }>(`
      SELECT COUNT(*)::int AS n,COALESCE(SUM(quantity_delta),0)::int AS qty
      FROM inventory_movements WHERE source_type='order_status_reversal'
    `);
    expect(result.rows[0]).toEqual({ n: 1, qty: 2 });
  });

  it("blocks new journals inside a closed period", async () => {
    await db.exec(`
      INSERT INTO accounting_period_closes(period_key,period_start,period_end,status)
      VALUES('2026-08','2026-08-01','2026-09-01','closed');
    `);
    await expect(db.exec(`
      INSERT INTO journal_entries(entry_date,period_key,source_type,source_id,event_kind,description,total_debit,total_credit)
      VALUES(now(),'2026-08','test','late','late_post','late',1,1)
    `)).rejects.toThrow(/CLOSED_PERIOD_JOURNAL_BLOCKED/);
  });
});
