import { build as esbuild } from "esbuild";
import { build as viteBuild } from "vite";
import { rm, readFile, rename, mkdir, writeFile } from "fs/promises";
import { generateHomeHeroModule } from "./prerender-home-hero.js";

// server deps to bundle to reduce openat(2) syscalls
// which helps cold start times
const allowlist = [
  "@google/generative-ai",
  "@neondatabase/serverless",
  "axios",
  "connect-pg-simple",
  "cors",
  "date-fns",
  "drizzle-orm",
  "drizzle-zod",
  "express",
  "express-rate-limit",
  "express-session",
  "jsonwebtoken",
  "memorystore",
  "multer",
  "nanoid",
  "nodemailer",
  "openai",
  "passport",
  "passport-local",
  "stripe",
  "uuid",
  "ws",
  "xlsx",
  "zod",
  "zod-validation-error",
];

async function buildAll() {
  await rm("dist", { recursive: true, force: true });

  console.log("building client...");
  await viteBuild();

  console.log("building server...");
  const pkg = JSON.parse(await readFile("package.json", "utf-8"));
  const allDeps = [
    ...Object.keys(pkg.dependencies || {}),
    ...Object.keys(pkg.devDependencies || {}),
  ];
  const externals = allDeps.filter((dep) => !allowlist.includes(dep));

  // Move index.html out of public so Vercel CDN doesn't serve it directly.
  // Write the template as a .ts file so SSR functions can import it directly.
  console.log("generating SSR template...");
  const htmlTemplate = await readFile("dist/public/index.html", "utf-8");
  await mkdir("dist/ssr-template", { recursive: true });
  await rename("dist/public/index.html", "dist/ssr-template/index.html");
  await rm("dist/public/index.html.br", { force: true });
  await rm("dist/public/index.html.gz", { force: true });
  await rm("dist/public/guides/5-mistakes", { recursive: true, force: true });
  await writeFile(
    "api/_html-template.ts",
    `// AUTO-GENERATED by build script — do not edit\nexport const HTML_TEMPLATE = ${JSON.stringify(htmlTemplate)};\n`,
  );

  // Prerender the homepage hero so the LCP element is in the initial HTML.
  // See script/prerender-home-hero.ts for why this runs from the real
  // component rather than a second copy of the markup.
  console.log("prerendering home hero...");
  await generateHomeHeroModule();

  // Keep the reviewed semantic SSR implementation separate from the stable
  // Vercel function entry. Build the self-contained runtime first; the tracked
  // api/ssr-preview.ts entry then imports this generated JavaScript artifact.
  // This makes repeated builds idempotent and prevents build output from
  // replacing the source file that the next clean build needs as its input.
  console.log("bundling semantic SSR runtime...");
  await mkdir("generated", { recursive: true });
  const generatedRuntimePath = "generated/ssr-preview-runtime.js";
  await rm(generatedRuntimePath, { force: true });
  await esbuild({
    entryPoints: ["api/_ssr-preview-source.ts"],
    platform: "node",
    bundle: true,
    format: "esm",
    outfile: generatedRuntimePath,
    define: {
      "process.env.NODE_ENV": '"production"',
    },
    external: allDeps,
    logLevel: "info",
    banner: {
      js: "import { createRequire } from 'module';const require = createRequire(import.meta.url);",
    },
  });

  const bundledRuntime = await readFile(generatedRuntimePath, "utf-8");
  const unresolvedLocalImport = /(?:from\s*["']\.{1,2}\/(?!node_modules)|import\(\s*["']\.{1,2}\/(?!node_modules))/;
  if (unresolvedLocalImport.test(bundledRuntime)) {
    throw new Error("Semantic SSR bundle still contains a relative runtime import");
  }
  if (!bundledRuntime.includes("semantic-v3") || !bundledRuntime.includes("noindex, follow")) {
    throw new Error("Semantic SSR bundle is missing required SEO safety contracts");
  }

  await esbuild({
    entryPoints: ["server/index.ts"],
    platform: "node",
    bundle: true,
    format: "esm",
    outfile: "dist/index.js",
    define: {
      "process.env.NODE_ENV": '"production"',
    },
    minify: true,
    external: externals,
    logLevel: "info",
    banner: {
      js: "import { createRequire } from 'module';const require = createRequire(import.meta.url);",
    },
  });
}

buildAll().catch((err) => {
  console.error(err);
  process.exit(1);
});
