import { build as esbuild } from "esbuild";
import { build as viteBuild } from "vite";
import { rm, readFile, rename, mkdir, writeFile } from "fs/promises";

// server deps to bundle to reduce openat(2) syscalls
// which helps cold start times
const allowlist = [
  "@google/generative-ai",
  "@neondatabase/serverless",
  "axios",
  "connect-pg-simple",
  "cors",
  "date-fns",
  "drizzle-orm",
  "drizzle-zod",
  "express",
  "express-rate-limit",
  "express-session",
  "jsonwebtoken",
  "memorystore",
  "multer",
  "nanoid",
  "nodemailer",
  "openai",
  "passport",
  "passport-local",
  "stripe",
  "uuid",
  "ws",
  "xlsx",
  "zod",
  "zod-validation-error",
];

async function buildAll() {
  await rm("dist", { recursive: true, force: true });

  console.log("building client...");
  await viteBuild();

  console.log("building server...");
  const pkg = JSON.parse(await readFile("package.json", "utf-8"));
  const allDeps = [
    ...Object.keys(pkg.dependencies || {}),
    ...Object.keys(pkg.devDependencies || {}),
  ];
  const externals = allDeps.filter((dep) => !allowlist.includes(dep));

  // Move index.html out of public so Vercel CDN doesn't serve it directly.
  // Write the template as a .ts file so SSR functions can import it directly.
  console.log("generating SSR template...");
  const htmlTemplate = await readFile("dist/public/index.html", "utf-8");
  await mkdir("dist/ssr-template", { recursive: true });
  await rename("dist/public/index.html", "dist/ssr-template/index.html");
  await rm("dist/public/index.html.br", { force: true });
  await rm("dist/public/index.html.gz", { force: true });
  await rm("dist/public/guides/5-mistakes", { recursive: true, force: true });
  await writeFile(
    "api/_html-template.ts",
    `// AUTO-GENERATED by build script — do not edit\nexport const HTML_TEMPLATE = ${JSON.stringify(htmlTemplate)};\n`,
  );

  // Vercel previously compiled api/ssr-preview.ts while leaving its local
  // helper imports as runtime files. Those helpers were not present in the
  // deployed function and caused FUNCTION_INVOCATION_FAILED. Bundle every
  // relative SEO/AEO/GEO module into one generated TypeScript runtime, then
  // replace the public function entry with a small canonical-host guard that
  // delegates to that one bundled file. Package dependencies remain external
  // and are provided by node_modules.
  console.log("bundling semantic SSR runtime...");
  await mkdir("generated", { recursive: true });
  const generatedRuntimePath = "generated/ssr-preview-runtime.ts";
  await esbuild({
    entryPoints: ["api/ssr-preview.ts"],
    platform: "node",
    bundle: true,
    format: "esm",
    outfile: generatedRuntimePath,
    define: {
      "process.env.NODE_ENV": '"production"',
    },
    external: allDeps,
    logLevel: "info",
    banner: {
      js: "import { createRequire } from 'module';const require = createRequire(import.meta.url);",
    },
  });

  const bundledRuntime = await readFile(generatedRuntimePath, "utf-8");
  const unresolvedLocalImport = /(?:from\s*["']\.{1,2}\/(?!node_modules)|import\(\s*["']\.{1,2}\/(?!node_modules))/;
  if (unresolvedLocalImport.test(bundledRuntime)) {
    throw new Error("Semantic SSR bundle still contains a relative runtime import");
  }
  if (!bundledRuntime.includes("semantic-v3") || !bundledRuntime.includes("noindex, follow")) {
    throw new Error("Semantic SSR bundle is missing required SEO safety contracts");
  }

  await writeFile(
    "api/ssr-preview.ts",
    `// AUTO-GENERATED production entry — source is bundled by script/build.ts
import type { VercelRequest, VercelResponse } from "@vercel/node";
import semanticRuntime from "../generated/ssr-preview-runtime.js";

const CANONICAL_ORIGIN = "https://www.aquavoiq.com";
const SEO_RELEASE_LAST_MODIFIED = "Tue, 04 Aug 2026 00:00:00 GMT";

function requestHost(req: VercelRequest): string {
  const forwarded = req.headers["x-forwarded-host"];
  const raw = Array.isArray(forwarded)
    ? forwarded[0]
    : forwarded || (Array.isArray(req.headers.host) ? req.headers.host[0] : req.headers.host) || "";
  return raw.split(",", 1)[0].trim().split(":", 1)[0].toLowerCase();
}

export default async function handler(req: VercelRequest, res: VercelResponse): Promise<void> {
  const host = requestHost(req);
  if (process.env.VERCEL_ENV === "production" && host && host !== "www.aquavoiq.com") {
    const destination = new URL(req.url || "/", CANONICAL_ORIGIN);
    res.setHeader("Location", destination.toString());
    res.setHeader("Cache-Control", "public, max-age=86400");
    res.setHeader("X-Robots-Tag", "noindex, follow");
    res.status(308).end();
    return;
  }

  if (process.env.VERCEL_ENV === "production") {
    res.setHeader("Last-Modified", SEO_RELEASE_LAST_MODIFIED);
  }
  await semanticRuntime(req, res);
}
`,
  );

  await esbuild({
    entryPoints: ["server/index.ts"],
    platform: "node",
    bundle: true,
    format: "esm",
    outfile: "dist/index.js",
    define: {
      "process.env.NODE_ENV": '"production"',
    },
    minify: true,
    external: externals,
    logLevel: "info",
    banner: {
      js: "import { createRequire } from 'module';const require = createRequire(import.meta.url);",
    },
  });
}

buildAll().catch((err) => {
  console.error(err);
  process.exit(1);
});
