import { build as esbuild } from "esbuild";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { pathToFileURL } from "node:url";
import { resolve } from "node:path";

/**
 * Prerender the homepage hero to static HTML at build time.
 *
 * The homepage ships an empty <div id="root">, so the hero image — the LCP
 * element — cannot paint until the React bundle has downloaded, parsed and
 * executed. Measured on production with Lighthouse mobile before this change:
 * LCP 6.6s, of which 3869ms was render delay, while the image itself finished
 * downloading at 941ms.
 *
 * Rendering the real HomeHero component here rather than hand-writing a second
 * copy of the markup keeps one source of truth: the component in
 * client/src/components/home/home-hero.tsx is what both the browser bundle and
 * this prerender use, so the two cannot drift.
 *
 * The output is injected inside #root by api/ssr-meta.ts. main.tsx mounts with
 * createRoot().render(), which clears the container before its first render, so
 * React replaces this markup instead of duplicating it, and no hydration is
 * involved — there is nothing to mismatch.
 */
export async function prerenderHomeHero(): Promise<string> {
  await mkdir("generated", { recursive: true });
  const entry = "generated/home-hero-entry.tsx";
  const bundle = "generated/home-hero-entry.mjs";

  await writeFile(
    entry,
    [
      'import { renderToStaticMarkup } from "react-dom/server";',
      'import { HomeHero } from "../client/src/components/home/home-hero";',
      "export const html = renderToStaticMarkup(<HomeHero />);",
      "",
    ].join("\n"),
  );

  await esbuild({
    entryPoints: [entry],
    outfile: bundle,
    platform: "node",
    format: "esm",
    bundle: true,
    jsx: "automatic",
    logLevel: "silent",
    define: { "process.env.NODE_ENV": '"production"' },
    alias: {
      "@": resolve("client/src"),
      // See script/wouter-static-link.tsx for why the router is stubbed here.
      wouter: resolve("script/wouter-static-link.tsx"),
    },
    banner: {
      js: [
        // react-dom/server is CJS and reaches for node builtins; without this
        // the ESM bundle throws 'Dynamic require of "util" is not supported'.
        "import { createRequire } from 'module';const require = createRequire(import.meta.url);",
      ].join(""),
    },
  });

  const module_ = (await import(`${pathToFileURL(resolve(bundle)).href}?t=${Date.now()}`)) as {
    html: string;
  };

  // React hoists <link rel="preload"> for images to the front of the markup.
  // index.html already carries the hero preload with the right fetchpriority
  // and imagesrcset, and that strategy is deliberate, so drop the duplicates
  // rather than emitting a second set of preloads into the body.
  const html = module_.html.replace(/^(?:<link rel="preload"[^>]*\/>)+/, "");

  if (!html.startsWith("<section")) {
    throw new Error(`prerendered home hero should start with <section>, got: ${html.slice(0, 80)}`);
  }
  if (!html.includes("iwagumi_aquascape_1765676307763.webp")) {
    throw new Error("prerendered home hero is missing the LCP image");
  }

  await rm(entry, { force: true });
  await rm(bundle, { force: true });
  return html;
}

/**
 * The header is `sticky top-0`, so it sits in normal flow and the hero starts
 * below it. Without reserving that space the hero would paint at the top of the
 * viewport and then be pushed down when React mounts the real header, turning a
 * perfect 0.00 CLS into a visible shift.
 *
 * navbar.tsx sizes its row with `flex h-16` and the element carries `border-b`,
 * and neither is responsive, so the reserved height is exactly the same at every
 * breakpoint. Reusing those classes here keeps the placeholder in step with the
 * real header instead of hard-coding a pixel value that could silently drift.
 */
const HEADER_PLACEHOLDER =
  '<div aria-hidden="true" class="sticky top-0 z-50 w-full border-b border-border bg-background/95">' +
  '<div class="mx-auto flex h-16 max-w-7xl items-center gap-2 px-3 sm:px-5 lg:px-6"></div>' +
  "</div>";

export async function generateHomeHeroModule(): Promise<void> {
  const hero = await prerenderHomeHero();
  await writeFile(
    "api/_home-hero-html.ts",
    "// AUTO-GENERATED by script/prerender-home-hero.ts — do not edit\n" +
      `export const HOME_HERO_HTML = ${JSON.stringify(HEADER_PLACEHOLDER + hero)};\n`,
  );
}

export async function readGeneratedHomeHero(): Promise<string> {
  return readFile("api/_home-hero-html.ts", "utf-8");
}
