import type { Product } from "./schema.js";

export const mockProducts: Product[] = [
  {
    id: "fluval-407",
    slug: "fluval-407",
    name: "فلتر كانستر Fluval 407",
    brand: "Fluval",
    category: "filtration",
    subcategory: "canister",
    description: "فلتر خارجي قوي لأحواض حتى 500 لتر مع أداء هادئ واستهلاك طاقة منخفض.",
    price: 285000,
    originalPrice: 310000,
    currency: "IQD",
    images: ["/stock_images/fluval_407_canister__4d80d974.jpg"],
    thumbnail: "/stock_images/fluval_407_canister__4d80d974.jpg",
    rating: 4.9,
    reviewCount: 48,
    stock: 12,
    lowStockThreshold: 4,
    isNew: false,
    isBestSeller: true,
    specifications: {
      difficulty: "medium",
      ecoFriendly: true,
      videoUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    },
    createdAt: new Date("2024-10-01"),
    updatedAt: new Date("2024-11-15"),
  },
  {
    id: "aquaclear-70",
    slug: "aquaclear-70",
    name: "فلتر شلال AquaClear 70",
    brand: "AquaClear",
    category: "filtration",
    subcategory: "hob",
    description: "فلتر ظهر الحوض الشهير بكفاءة عالية وتدفق قابل للتعديل لأحواض 150-265 لتر.",
    price: 125000,
    originalPrice: 145000,
    currency: "IQD",
    images: ["/stock_images/aquaclear_70_power_f_dfd543e8.jpg"],
    thumbnail: "/stock_images/aquaclear_70_power_f_dfd543e8.jpg",
    rating: 4.6,
    reviewCount: 32,
    stock: 20,
    lowStockThreshold: 5,
    isNew: false,
    isBestSeller: true,
    specifications: {
      difficulty: "easy",
      ecoFriendly: true,
    },
    createdAt: new Date("2024-08-12"),
    updatedAt: new Date("2024-11-20"),
  },
  {
    id: "seachem-prime",
    slug: "seachem-prime-500ml",
    name: "مُكيف مياه Seachem Prime 500ml",
    brand: "Seachem",
    category: "water-care",
    subcategory: "conditioner",
    description: "إزالة الكلور والكلورامين وتحييد الأمونيا لحماية الأسماك خلال تغييرات المياه.",
    price: 55000,
    currency: "IQD",
    images: ["/stock_images/seachem_prime_500ml__b70abe42.jpg"],
    thumbnail: "/stock_images/seachem_prime_500ml__b70abe42.jpg",
    rating: 4.8,
    reviewCount: 67,
    stock: 40,
    lowStockThreshold: 6,
    isNew: false,
    isBestSeller: true,
    specifications: {
      difficulty: "easy",
      ecoFriendly: true,
    },
    createdAt: new Date("2024-07-02"),
    updatedAt: new Date("2024-11-10"),
  },
  {
    id: "eheim-jager-200w",
    slug: "eheim-jager-200w",
    name: "سخان EHEIM Jager 200W",
    brand: "EHEIM",
    category: "heating",
    subcategory: "heater",
    description: "سخان زجاجي دقيق مع حماية من الجفاف وتصحيح حرارة عالي الدقة.",
    price: 95000,
    currency: "IQD",
    images: ["/stock_images/eheim_jager_aquarium_f65664bd.jpg"],
    thumbnail: "/stock_images/eheim_jager_aquarium_f65664bd.jpg",
    rating: 4.7,
    reviewCount: 28,
    stock: 18,
    lowStockThreshold: 5,
    isNew: false,
    isBestSeller: true,
    specifications: {
      difficulty: "easy",
      ecoFriendly: false,
    },
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2024-11-05"),
  },
  {
    id: "anubias-nana",
    slug: "anubias-nana",
    name: "نبتة حية Anubias Nana",
    brand: "Aquatic Plants",
    category: "plants",
    subcategory: "rhizome",
    description: "نبتة منخفضة الإضاءة تُربط على الأخشاب والصخور، مثالية للمبتدئين.",
    price: 35000,
    currency: "IQD",
    images: ["/stock_images/anubias_nana_aquariu_554af5dc.jpg"],
    thumbnail: "/stock_images/anubias_nana_aquariu_554af5dc.jpg",
    rating: 4.5,
    reviewCount: 18,
    stock: 25,
    lowStockThreshold: 6,
    isNew: true,
    isBestSeller: false,
    specifications: {
      difficulty: "easy",
      ecoFriendly: true,
    },
    createdAt: new Date("2024-09-10"),
    updatedAt: new Date("2024-11-18"),
  },
  {
    id: "wave-maker-6-port",
    slug: "wave-maker-6-port",
    name: "موزع هواء 6 مخارج للأحواض",
    brand: "Generic",
    category: "aeration",
    subcategory: "manifold",
    description: "موزع معدني بستة مخارج للتحكم بتوزيع الهواء في أكثر من حوض بسهولة.",
    price: 24000,
    currency: "IQD",
    images: ["/products/6-port-blue-201.jpg"],
    thumbnail: "/products/6-port-blue-201.jpg",
    rating: 4.3,
    reviewCount: 14,
    stock: 30,
    lowStockThreshold: 8,
    isNew: false,
    isBestSeller: false,
    specifications: {
      difficulty: "easy",
      ecoFriendly: false,
    },
    createdAt: new Date("2024-05-15"),
    updatedAt: new Date("2024-11-12"),
  },
  {
    id: "activated-carbon-500g",
    slug: "activated-carbon-500g",
    name: "فحم منشط للأحواض 500 غرام",
    brand: "ClearWater",
    category: "filtration-media",
    subcategory: "chemical",
    description: "فحم منشط عالي المسامية لإزالة الروائح والمواد العضوية وتحسين شفافية المياه.",
    price: 28000,
    currency: "IQD",
    images: ["/products/activated-carbon-189.jpg"],
    thumbnail: "/products/activated-carbon-189.jpg",
    rating: 4.4,
    reviewCount: 22,
    stock: 35,
    lowStockThreshold: 10,
    isNew: false,
    isBestSeller: false,
    specifications: {
      difficulty: "easy",
      ecoFriendly: false,
    },
    createdAt: new Date("2024-04-08"),
    updatedAt: new Date("2024-11-08"),
  },
  {
    id: "water-test-kit",
    slug: "water-test-kit",
    name: "شريط فحص جودة المياه (9 في 1)",
    brand: "AquaLab",
    category: "testing",
    subcategory: "strips",
    description: "شرائط اختبار فورية لقياس الأمونيا والنيتريت والنترات والكلور والـ pH.",
    price: 22000,
    currency: "IQD",
    images: ["/products/9-in-one-water-quality-test-paper-aluminum-foil-bag-138.jpg"],
    thumbnail: "/products/9-in-one-water-quality-test-paper-aluminum-foil-bag-138.jpg",
    rating: 4.2,
    reviewCount: 31,
    stock: 28,
    lowStockThreshold: 8,
    isNew: true,
    isBestSeller: false,
    specifications: {
      difficulty: "easy",
      ecoFriendly: true,
    },
    createdAt: new Date("2024-09-25"),
    updatedAt: new Date("2024-11-22"),
  },
];
