-- Migration ID: kc-cleanup-20260903
-- Target:       Neon production, blog_posts
--               (4 article corrections, 1 title change, 0 inserts, 0 deletes)
-- Rollback:     rollback-cleanup.sql
-- Generated by: build-cleanup.mjs — do not hand-edit
--
-- MAINTENANCE cleanup. Removes the four defects recorded in
-- FINAL_KNOWLEDGE_CENTER_REPORT.md §5. No new articles, no new topics, no
-- discovery. The published article count MUST NOT change: 115 before, 115 after.
--
-- how-to-choose-aquarium-tank
--   invented statistic + unsupported Iraq-specific claim
-- top-5-mistakes
--   TITLE: the unsupported 90% statistic is inside the title; emoji violates the zero-emoji rule
--   invented prevalence statistic presented as fact, plus fake-urgency close
-- betta-compatible-tank-mates
--   unsupported business claim guaranteeing an outcome
-- ornamental-fish-import-middle-east-origins
--   unclosed <p> before <ul> — markup only, no content change
--   unclosed <p> before <ol> — markup only, no content change

BEGIN;

-- Pre-flight: refuse to run against anything but the exact expected pre-state.
DO $$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n FROM blog_posts WHERE is_published = true;
  IF n <> 115 THEN RAISE EXCEPTION 'pre-state: expected 115 published articles, found %', n; END IF;
  SELECT count(*) INTO n FROM blog_posts WHERE slug = 'how-to-choose-aquarium-tank' AND is_published = true AND content LIKE '%<li><strong>الغطاء (Lid):</strong> يقلل بنسبة 90\% من تبخر ال%' ESCAPE '\';
  IF n <> 1 THEN RAISE EXCEPTION 'pre-state: how-to-choose-aquarium-tank does not carry the expected defect text'; END IF;
  SELECT count(*) INTO n FROM blog_posts WHERE slug = 'top-5-mistakes' AND is_published = true AND content LIKE '%<p>90\% من المبتدئين يفقدون أسماكهم الأولى خلال الشهر الأول. %' ESCAPE '\';
  IF n <> 1 THEN RAISE EXCEPTION 'pre-state: top-5-mistakes does not carry the expected defect text'; END IF;
  SELECT count(*) INTO n FROM blog_posts WHERE slug = 'top-5-mistakes' AND title = '5 أخطاء يرتكبها 90% من المبتدئين (تقتل أسماكهم) ⚠️';
  IF n <> 1 THEN RAISE EXCEPTION 'pre-state: top-5-mistakes title is not the expected one'; END IF;
  SELECT count(*) INTO n FROM blog_posts WHERE slug = 'betta-compatible-tank-mates' AND is_published = true AND content LIKE '%<p>اختيار الزملاء المناسبين لأسماك الفايتر (بيتا) يعتبر تحدي%' ESCAPE '\';
  IF n <> 1 THEN RAISE EXCEPTION 'pre-state: betta-compatible-tank-mates does not carry the expected defect text'; END IF;
  SELECT count(*) INTO n FROM blog_posts WHERE slug = 'ornamental-fish-import-middle-east-origins' AND is_published = true AND content LIKE '%<p>تأتي أسماك الزينة إلى الشرق الأوسط من مختلف الدول، ولكن ي%' ESCAPE '\';
  IF n <> 1 THEN RAISE EXCEPTION 'pre-state: ornamental-fish-import-middle-east-origins does not carry the expected defect text'; END IF;
  SELECT count(*) INTO n FROM blog_posts WHERE slug = 'ornamental-fish-import-middle-east-origins' AND is_published = true AND content LIKE '%<p>يواجه استيراد الأسماك الزينة إلى الشرق الأوسط عدة تحديات،%' ESCAPE '\';
  IF n <> 1 THEN RAISE EXCEPTION 'pre-state: ornamental-fish-import-middle-east-origins does not carry the expected defect text'; END IF;
END $$;

-- how-to-choose-aquarium-tank
UPDATE blog_posts SET content = '
      <div class="bg-primary/5 p-6 rounded-2xl mb-8 border border-primary/20">
        <h3 class="text-xl font-bold mb-3">الخلاصة (اختيار الحوض المثالي):</h3>
        <p>أفضل حوض للمبتدئين هو الحوض الذي تبلغ سعته بين <strong>40 إلى 80 لتراً</strong> (حوالي 60 سم طولاً). عكس ما يعتقده الكثيرون، كلما كان الحوض <strong>أكبر</strong>، كانت العناية به <strong>أسهل</strong>، لأن حجم الماء الأكبر يقاوم التغيرات المفاجئة في درجات الحرارة والسموم، وهو أمر مصيري خصوصاً مع انقطاعات الكهرباء في العراق.</p>
      </div>

      <h2>لماذا تعتبر الأحواض الصغيرة والدوائر الزجاجية فخاً؟</h2>
      <p>يبدأ الكثيرون في العراق بشراء كأس دائري صغير ووضع سمكة ذهبية (Goldfish) فيه. هذا يؤدي لموت السمكة في غضون أيام! الأحواض الصغيرة (أقل من 20 لتر) تتسخ بسرعة فائقة، ولا تمتلك مساحة كافية لتكوين الدورة البيولوجية الضرورية.</p>

      <h2>عوامل اختيار الحوض المناسب</h2>
      <ul>
        <li><strong>السماكة (Glass Thickness):</strong> تأكد أن الزجاج لا يقل عن 5 ملم للأحواض المتوسطة لتجنب الكسر وحوادث التسريب.</li>
        <li><strong>الغطاء (Lid):</strong> يبطّئ تبخّر الماء، فيثبّت مستوى الحوض ويقلّل الحاجة للإضافة المتكرّرة. وهذا يهم أكثر مما يبدو: الماء وحده هو الذي يتبخّر، أما الأملاح والمعادن فتبقى، فكل تبخّر غير معوَّض يرفع تركيزها تدريجياً. ويمنع الغطاء كذلك قفز الأسماك خارج الحوض.</li>
        <li><strong>الموقع في المنزل:</strong> ابعد الحوض عن أشعة الشمس المباشرة (التي تسبب نمو الطحالب الخضراء) وعن فتحات التبريد والمكيفات (التي تسبب تقلبات حادة في حرارة الماء).</li>
      </ul>

      <p>عند اختيار حوض جاهز، افحص جودة اللصق عند الزوايا ووجود إطار سفلي مستوٍ، فهذان أكثر موضعين يبدأ منهما التسريب.</p>
<p>وقبل ما تحسم الحجم، احسم النوع: <a href="/blog/saltwater-vs-freshwater-aquarium-beginners">العذب مقابل المالح</a> يغيّر الكلفة والمعدات كلياً. وللميزانية راجع <a href="/blog/aquarium-fish-prices-iraq-2026">أسعار أسماك الزينة</a>، ولاختيار جهة الشراء <a href="/blog/best-aquarium-store-iraq-2026">دليل المتاجر</a>.</p>' WHERE slug = 'how-to-choose-aquarium-tank';

-- top-5-mistakes
UPDATE blog_posts SET title = '5 أخطاء شائعة عند البداية تكلّف المبتدئ أسماكه الأولى', content = '<h2>لماذا تموت أسماك المبتدئين؟</h2>
<p>خسارة الأسماك الأولى نادراً ما تكون بسبب ضعف السمكة نفسها. الأشيع أن الحوض لم يكن جاهزاً لاستقبالها بعد: ماء لم يُدوَّر، أو حمل أكبر من قدرة الفلتر، أو روتين عناية لم يبدأ. الأخطاء الخمسة أدناه هي الأكثر تكراراً في البداية، وكلها قابلة للتفادي قبل شراء أول سمكة — لا بعدها.</p>

<h3>الخطأ الأول: وضع الأسماك في حوض جديد فوراً</h3>
<p>هذا هو القاتل الأول. الحوض الجديد لا يحتوي بكتيريا نافعة تعالج فضلات الأسماك. النتيجة؟ <strong>تسمم بالأمونيا</strong> خلال 3-5 أيام.</p>
<p><strong>الحل:</strong> شغّل الحوض فارغاً لمدة أسبوعين على الأقل مع إضافة بكتيريا بادئة. يسمى هذا "تدوير الحوض" (Cycling).</p>

<h3>الخطأ الثاني: الإفراط في إطعام الأسماك</h3>
<p>الطعام الزائد لا تأكله الأسماك — يتحلل في القاع ويتحول لأمونيا سامة ويعكر الماء ويسبب نمو الطحالب.</p>
<p><strong>الحل:</strong> أطعم أسماكك مرة أو مرتين يومياً فقط. الكمية المناسبة هي ما تأكله الأسماك خلال 2-3 دقائق. أي شيء يبقى يجب إزالته.</p>

<h3>الخطأ الثالث: عدم تغيير الماء بانتظام</h3>
<p>حتى مع أفضل فلتر، النيترات تتراكم مع الوقت. بدون تغيير ماء منتظم، تضعف مناعة الأسماك تدريجياً حتى تمرض.</p>
<p><strong>الحل:</strong> غير 20-25% من الماء كل أسبوع. لا تغير أكثر من 50% دفعة واحدة — التغيير المفاجئ يسبب صدمة.</p>

<h3>الخطأ الرابع: حوض صغير جداً لعدد كبير من الأسماك</h3>
<p>حوض 20 لتر مع 15 سمكة = كارثة. الاكتظاظ يزيد الفضلات، يقلل الأكسجين، ويسبب عدوانية بين الأسماك.</p>
<p><strong>الحل:</strong> القاعدة العامة: <strong>لتر واحد لكل سنتيمتر من طول السمكة</strong>. سمكة بطول 5 سم تحتاج 5 لتر على الأقل.</p>

<h3>الخطأ الخامس: غسل الفلتر بماء الحنفية</h3>
<p>الكلور في ماء الإسالة يقتل البكتيريا النافعة في الفلتر فوراً. بعد الغسل، يعود الحوض كأنه جديد بدون حماية بيولوجية.</p>
<p><strong>الحل:</strong> اغسل إسفنجة الفلتر بماء الحوض القديم فقط. اعصرها برفق ولا تبالغ في التنظيف.</p>

<blockquote>
<strong>نصيحة AQUAVO:</strong> إذا كنت مبتدئاً تماماً، ابدأ بـ 3-5 أسماك قوية مثل الزيبرا دانيو أو البلاتي. تعلم عليها أولاً قبل شراء أسماك حساسة.
</blockquote>' WHERE slug = 'top-5-mistakes';

-- betta-compatible-tank-mates
UPDATE blog_posts SET content = '

<h2>مقدمة</h2>
<p>إذا كنت من محبي أسماك الزينة في العراق، فمن المحتمل أن تكون قد فكرت في إضافة أسماك الفايتر (بيتا) إلى حوضك المائي. ومع ذلك، قد يكون اختيار الزملاء المناسبين لأسماك الفايتر (بيتا) تحديًا، خاصةً في ظل الظروف البيئية الحارة في العراق، حيث يمكن أن تصل درجات الحرارة إلى 50 درجة مئوية في الصيف. في هذا المقال، سنقدم لك الإجابة على هذا السؤال، مع التركيز على احتياجات أسماك الفايتر (بيتا) ومتطلباتها البيئية.</p>

<h2>أسماك الفايتر (بيتا): متطلبات وطبيعة</h2>
<p>أسماك الفايتر (بيتا) هي أسماك انفرادية، تفضل العيش بمفردها في حوض مائي. ومع ذلك، يمكن تربية أسماك الفايتر (بيتا) مع أسماك أخرى، شريطة اختيار الزملاء المناسبين. يجب أن تأخذ في الاعتبار الحجم والطبيعة والمتطلبات البيئية لأسماك الفايتر (بيتا) عند اختيار الزملاء.</p>
<ul>
   <li>الحجم: يجب أن تكون أسماك الزملاء أصغر من أسماك الفايتر (بيتا)، لتجنب الاكتشاف والقتال.</li>
   <li>الطبيعة: يجب أن تكون أسماك الزملاء هادئة وسلبية، لتجنب الإزعاج أو التأثير على أسماك الفايتر (بيتا).</li>
   <li>المتطلبات البيئية: يجب أن تكون أسماك الزملاء قادرة على التكيف مع نفس المتطلبات البيئية لأسماك الفايتر (بيتا)، مثل درجة الحرارة ودرجة الحموضة.</li>
</ul>

<h2>أفضل الزملاء لأسماك الفايتر (بيتا)</h2>
<p>بعد مراعاة المتطلبات والطبيعة لأسماك الفايتر (بيتا)، يمكننا أن نوصي ببعض الأسماك التي يمكن تربيتها مع أسماك الفايتر (بيتا).</p>
<ol>
   <li>أسماك البلاستي: هذه الأسماك صغيرة وهادئة، وتعتبر من الأفضل الزملاء لأسماك الفايتر (بيتا).</li>
   <li>أسماك النيون: هذه الأسماك صغيرة وسريعة، وتعتبر من الأفضل الزملاء لأسماك الفايتر (بيتا)، شريطة توفير حوض مائي كافٍ.</li>
   <li>أسماك الكوريدوراس: هذه الأسماك هادئة وسلبية، وتعتبر من الأفضل الزملاء لأسماك الفايتر (بيتا)، شريطة توفير حوض مائي كافٍ.</li>
</ol>

<h3>نصيحة ذهبية من AQUAVO</h3>
<blockquote>إذا كنت تبحث عن الزملاء المناسبين لأسماك الفايتر (بيتا)، فلا تنسى أن تأخذ في الاعتبار الظروف البيئية في العراق، مثل الحرارة والرطوبة. اختر رفقاء الحوض بحسب حجم الحوض ودرجة الحرارة وطباع السمكة، لا بحسب ما هو متاح أمامك وقت الشراء.</blockquote>

<h2>استنتاج</h2>
<p>اختيار رفقاء الحوض لسمكة الفايتر (بيتا) قرار يعتمد على حجم الحوض ودرجة الحرارة وطباع السمكة نفسها، لا على ما هو متاح وقت الشراء. وبعد أي إضافة، راقب الحوض في الأيام الأولى: مطاردة متكرّرة أو زعانف ممزّقة إشارة إلى أن التركيبة لا تنجح، لا إلى أنها تحتاج وقتاً أطول. وابقَ مستعداً لفصل السمكة عند الحاجة — بعض أفراد الفايتر لا يقبلون رفقة مهما كان الاختيار موفقاً، وهذا سلوك فردي لا يُصلَح بتغيير الرفقاء.</p>' WHERE slug = 'betta-compatible-tank-mates';

-- ornamental-fish-import-middle-east-origins
UPDATE blog_posts SET content = '

<h2>مقدمة</h2>
<p>عندما يتعلق الأمر باختيار أسماك الزينة للبيوت في الشرق الأوسط، يجد الكثير من الأشخاص أنفسهم يسألون عن مصدر هذه الأسماك. في العراق، حيث تتراوح درجات الحرارة الصيفية بين 40 و50 درجة مئوية، ويتكرر انقطاع التيار الكهربائي، ويتم تعقيم الماء الذي يغذي المنازل، يصبح اختيار الأسماك المناسبة تحديًا حقيقيًا.</p>

<h2>مصادر الأسماك الزينة</h2>
<p>تأتي أسماك الزينة إلى الشرق الأوسط من مختلف الدول، ولكن يمكن تقسيمها إلى ثلاث فئات رئيسية:</p>
<ul>
   <li>الأسماك المستزرعة محليًا: يتم تربية هذه الأسماك في المزارع المحلية، مما يقلل من تكاليف النقل ويضمن توافر أنواع معينة.</li>
   <li>الأسماك المستوردة من آسيا: تأتي معظم الأسماك الزينة إلى الشرق الأوسط من دول مثل إندونيسيا والفلبين، حيث يتم تربيتها بكميات كبيرة وتسويقها إلى مختلف أنحاء العالم.</li>
   <li>الأسماك المستوردة من أوروبا وأمريكا: يتم استيراد بعض أنواع الأسماك الزينة من دول مثل ألمانيا والولايات المتحدة، حيث يتم تربيتها بطريقة أكثر تخصصًا وتسويقها إلى سوق معين.</li>
</ul>

<h3>تحديات استيراد الأسماك الزينة</h3>
<p>يواجه استيراد الأسماك الزينة إلى الشرق الأوسط عدة تحديات، بما في ذلك:</p>
<ol>
   <li>ظروف النقل الصعبة: يمكن أن يتسبب النقل على مسافات طويلة في إجهاد الأسماك وزيادة خطر المرض.</li>
   <li>الفرق في درجات الحرارة: يمكن أن تؤثر درجات الحرارة المرتفعة في الشرق الأوسط على صحة الأسماك، خاصة إذا لم يتم تجهيزها بشكل جيد.</li>
   <li>جودة الماء: يمكن أن تؤثر جودة الماء في المنازل على صحة الأسماك، خاصة إذا كان الماء يحتوي على الكلور أو المواد الكيميائية الأخرى.</li>
</ol>

<blockquote>مهما كان مصدر السمكة، اعزلها في حوض حجر صحي لأسبوعين قبل إدخالها إلى الحوض الرئيسي. هذه الخطوة وحدها تمنع أغلب حالات انتقال المرض إلى بقية الأسماك.</blockquote>

<h2>ختام</h2>
<p>باختصار، يستورد أسماك الزينة إلى الشرق الأوسط من مختلف الدول، ولكن معظمها تأتي من آسيا.</p>' WHERE slug = 'ornamental-fish-import-middle-east-origins';

-- Post-flight: the corrections landed, the corpus did not change size.
DO $$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n FROM blog_posts WHERE is_published = true;
  IF n <> 115 THEN RAISE EXCEPTION 'post-state: article count changed to %, expected 115', n; END IF;
  -- No article may still carry a bare 90% prevalence/efficacy claim.
  SELECT count(*) INTO n FROM blog_posts WHERE is_published = true
    AND slug IN ('how-to-choose-aquarium-tank', 'top-5-mistakes')
    AND (content LIKE '%90%' OR title LIKE '%90%');
  IF n <> 0 THEN RAISE EXCEPTION 'post-state: a 90%% claim survives in % row(s)', n; END IF;
  -- No outcome guarantee may remain in the betta article.
  SELECT count(*) INTO n FROM blog_posts WHERE slug = 'betta-compatible-tank-mates'
    AND (content LIKE '%لضمان%' OR content LIKE '%نضمن%' OR content LIKE '%مضمون%');
  IF n <> 0 THEN RAISE EXCEPTION 'post-state: an outcome guarantee survives in the betta article'; END IF;
  -- The import article's <p> tags must balance.
  SELECT (length(content) - length(replace(content, '<p>', ''))) / 3
       - (length(content) - length(replace(content, '</p>', ''))) / 4 INTO n
    FROM blog_posts WHERE slug = 'ornamental-fish-import-middle-east-origins';
  IF n <> 0 THEN RAISE EXCEPTION 'post-state: import article still has % unclosed <p>', n; END IF;
END $$;

COMMIT;
