export const DELIVERY_FEE = 5000;
export const BAGHDAD_SHIPPING = DELIVERY_FEE;
export const OTHER_GOVERNORATES_SHIPPING = DELIVERY_FEE;
export const DELIVERY_DAYS = "تُحدّد حسب الوجهة والطلب";
export const BAGHDAD_DELIVERY_DAYS = DELIVERY_DAYS;
export const OTHER_DELIVERY_DAYS = DELIVERY_DAYS;
export const DELIVERY_TEXT = "تظهر أجرة ومدة التوصيل المتوقعة قبل تأكيد الطلب";
export const WHATSAPP_NUMBER = "9647747880673";
export const WHATSAPP_URL = `https://wa.me/${WHATSAPP_NUMBER}`;
