-- Migration ID: blog-claims-truth-batch4-20260902
-- Target:       Neon production, blog_posts
-- Rollback:     rollback.sql (restores content and excerpt from the backup table)
--
-- Corpus-wide claims audit, batch 4. This is a different defect class from
-- script contamination: the generator asserted business facts it had no source
-- for. Ground truth is the live catalogue, the governorate list, the shipping
-- constants and the published policy pages. See audit.md for the full ledger,
-- including the claims that were checked and KEPT.
--
-- 18 corrections across 15 articles.
-- Generated by build.mjs, which verified every target against live production
-- and proved the banned claims are gone corpus-wide before emitting.

BEGIN;

DO $$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n FROM blog_posts WHERE is_published;
  IF n <> 80 THEN RAISE EXCEPTION 'expected 80 published posts, found %', n; END IF;
END $$;

CREATE TABLE blog_posts_backup_claims_b4_20260902 AS
SELECT id, slug, title, excerpt, content, is_published, now() AS backed_up_at
  FROM blog_posts;

-- Pre-flight: every target must still be present at its expected count.
DO $$
DECLARE bad text;
BEGIN
  SELECT string_agg(t.slug || ' :: ' || left(t.frag, 60), chr(10)) INTO bad
    FROM (VALUES
      ('aquarium-bedroom-feng-shui-sound-effect', 'لدينا ضمانات طويلة الأجل وخدمة توصيل سريعة إلى جميع أنحاء البلاد.', 1, 'content'),
      ('human-medicine-dangers-for-fish', 'حيث نقدم مجموعة واسعة من الأدوية السمكية و منتجات الرعاية الصحية للأسماك، مع ضمانات و توصيل إلى 18 محافظة في العراق.', 1, 'content'),
      ('amazon-sword-plant-care-propagation', 'ضمان جودة: متجر AQUAVO يوفر ضمان جودة على جميع المنتجات.', 1, 'content'),
      ('black-beard-algae-removal-steps', 'يمكن أن توفر AQUAVO منتجات عالية الجودة وموثوقة، مع ضمانات وخدمة عملاء ممتازة.', 1, 'content'),
      ('iwagumi-aquascape-step-by-step', 'ويمكن استخدام خدمات شركة AQUAVO التي توفر أفضل أنواع المكونات وضمانات لجميع المنتجات، بالإضافة إلى خدمات التوصيل إلى جميع محافظات العراق.', 2, 'content'),
      ('air-pumps-decoration-or-necessity', 'جميع منتجاتنا مدعومة بضمانات مطولة، وتتوفر للاستلام في جميع أنحاء العراق عبر 18 محافظة.', 1, 'content'),
      ('cloudy-aquarium-water-causes-fix', 'متجر AQUAVO يعتبر الوجهة الأولى للمهتمين بتربية الأسماك في العراق، حيث يوفر مواد مرشحة عالية الجودة وضمانات طويلة الأمد، وتوصيل المنتجات إلى جميع محافظات العراق البالغ عددها 18 محافظة.', 1, 'content'),
      ('activated-carbon-aquarium-when-to-use', 'نوصي باستخدام الفحم النشط من ماركات موثوقة، مثل تلك التي تقدمها AQUAVO، التي توفر منتجات عالية الجودة وضمانات طويلة الأمد.', 1, 'content'),
      ('activated-carbon-aquarium-when-to-use', 'نحن في AQUAVO، نسعد بتقديم منتجات عالية الجودة وضمانات طويلة الأمد، بما في ذلك الفحم النشط، لجميع عملائنا في العراق.', 1, 'content'),
      ('african-cichlids-best-types-colors', 'يمكنك الاستفادة من خدمات وضمانات AQUAVO، التي تضم مجموعة واسعة من المنتجات عالية الجودة والمستوردة، والذي يغطي 18 محافظة في العراق.', 2, 'content'),
      ('molly-platy-breeding-save-fry', 'بالإضافة إلى ذلك، فإن AQUAVO توفر ضمانات لجميع منتجاتها، وتقدم خدمة توصيل إلى جميع أنحاء العراق، بما في ذلك 18 محافظة.', 1, 'content'),
      ('fin-rot-treatment-guide', 'كما يوفر متجر AQUAVO خدمات التوصيل إلى جميع محافظات العراق البالغ عددها 18 محافظة، ويوفر ضمانات على جميع المنتجات.', 1, 'content'),
      ('fish-keeping-stress-relief-mental-health', 'ويقدم ضمانات وخدمات توصيل إلى 18 محافظة في العراق. بالإضافة إلى ذلك، يقدم <strong>AQUAVO</strong> منتجات عالية الجودة ومستوردة من أفضل الشركات في العالم.', 1, 'content'),
      ('aquarium-soil-volcanic-substrate-secrets', 'وتعد منتجات AQUAVO المصرح بها ومستوردة من أفضل المصانع العالمية خياراً مثاليًا لمحبي الأسماك في العراق، مع ضمانات وخدمة توصيل إلى جميع المحافظات الـ 18.', 1, 'content'),
      ('aquarium-soil-volcanic-substrate-secrets', 'يمكنهم الحصول على التربة البركانية وجميع المنتجات اللازمة لإنشاء حوض سمك مثالي من متجر AQUAVO، مع ضمان جودة وخدمة توصيل سريعة إلى جميع المناطق.', 1, 'content'),
      ('filter-media-ceramic-rings-bioballs', 'بالإضافة إلى ذلك، نقدم لك مجموعة واسعة من المنتجات المستوردة من أفضل الشركات العالمية، والتي تُعتبر من أفضل الخيارات لآحواض المائية في العراق.', 1, 'content'),
      ('fin-rot-treatment-guide', 'حيث يُقدم مجموعة واسعة من المنتجات عالية الجودة والمستوردة من أفضل الشركات العالمية.', 1, 'content'),
      ('best-aquarium-store-iraq-2026', 'تعرف على أول وأكبر متجر إلكتروني متخصص في أسماك الزينة ومستلزمات الأحواض في العراق (AQUAVO) ولماذا يتفوق على الأسواق التقليدية.', 1, 'excerpt')
    ) AS t(slug, frag, want, col)
    LEFT JOIN blog_posts b ON b.slug = t.slug
   WHERE b.id IS NULL
      OR (length(CASE t.col WHEN 'excerpt' THEN b.excerpt ELSE b.content END)
          - length(replace(CASE t.col WHEN 'excerpt' THEN b.excerpt ELSE b.content END, t.frag, '')))
         / nullif(length(t.frag), 0) <> t.want;
  IF bad IS NOT NULL THEN
    RAISE EXCEPTION 'live content changed since drafting; bad targets: %', bad;
  END IF;
END $$;

-- aquarium-bedroom-feng-shui-sound-effect · content (1 correction)
--   REMOVE · Long-term warranties across the store. The return policy grants none.
UPDATE blog_posts SET content = replace(content, 'لدينا ضمانات طويلة الأجل وخدمة توصيل سريعة إلى جميع أنحاء البلاد.', 'ولدينا خدمة توصيل إلى 18 محافظة في العراق.')
 WHERE slug = 'aquarium-bedroom-feng-shui-sound-effect';

-- human-medicine-dangers-for-fish · content (1 correction)
--   REMOVE · Blanket warranty removed; the medicines are genuinely stocked and the delivery term is verified, so both stay.
UPDATE blog_posts SET content = replace(content, 'حيث نقدم مجموعة واسعة من الأدوية السمكية و منتجات الرعاية الصحية للأسماك، مع ضمانات و توصيل إلى 18 محافظة في العراق.', 'حيث نقدم أدوية ومعالجات مياه للأحواض، مع توصيل إلى 18 محافظة في العراق.')
 WHERE slug = 'human-medicine-dangers-for-fish';

-- amazon-sword-plant-care-propagation · content (1 correction)
--   REMOVE · A quality warranty on every product. Replaced with support, which is real.
UPDATE blog_posts SET content = replace(content, 'ضمان جودة: متجر AQUAVO يوفر ضمان جودة على جميع المنتجات.', 'دعم فني: متجر AQUAVO يوفر دعماً فنياً لهواة تربية الأسماك.')
 WHERE slug = 'amazon-sword-plant-care-propagation';

-- black-beard-algae-removal-steps · content (1 correction)
--   REMOVE · Blanket warranty removed; the named categories exist (13 SKUs in معالجة المياه, including two algae removers).
UPDATE blog_posts SET content = replace(content, 'يمكن أن توفر AQUAVO منتجات عالية الجودة وموثوقة، مع ضمانات وخدمة عملاء ممتازة.', 'يمكن أن توفر AQUAVO منتجات معالجة المياه ومزيلات الطحالب، مع خدمة عملاء.')
 WHERE slug = 'black-beard-algae-removal-steps';

-- iwagumi-aquascape-step-by-step · content (1 correction)
--   REMOVE · Warranty for all products, plus an unsupported 'best'. The aquascaping materials are real (27 SKUs in تربة وديكور) and the governorate count is now the verified one.
UPDATE blog_posts SET content = replace(content, 'ويمكن استخدام خدمات شركة AQUAVO التي توفر أفضل أنواع المكونات وضمانات لجميع المنتجات، بالإضافة إلى خدمات التوصيل إلى جميع محافظات العراق.', 'ويمكن استخدام خدمات AQUAVO التي توفر مواد الأكواسكيب والتربة والصخور، بالإضافة إلى التوصيل إلى 18 محافظة في العراق.')
 WHERE slug = 'iwagumi-aquascape-step-by-step';

-- air-pumps-decoration-or-necessity · content (1 correction)
--   REMOVE · Extended warranties on everything. The delivery half is verified and is kept.
UPDATE blog_posts SET content = replace(content, 'جميع منتجاتنا مدعومة بضمانات مطولة، وتتوفر للاستلام في جميع أنحاء العراق عبر 18 محافظة.', 'وتتوفر منتجاتنا للتوصيل عبر 18 محافظة في العراق.')
 WHERE slug = 'air-pumps-decoration-or-necessity';

-- cloudy-aquarium-water-causes-fix · content (1 correction)
--   REMOVE · Two claims in one sentence: 'the first destination' and long-term warranties. Filtration media is real (18 SKUs) and the delivery term is verified.
UPDATE blog_posts SET content = replace(content, 'متجر AQUAVO يعتبر الوجهة الأولى للمهتمين بتربية الأسماك في العراق، حيث يوفر مواد مرشحة عالية الجودة وضمانات طويلة الأمد، وتوصيل المنتجات إلى جميع محافظات العراق البالغ عددها 18 محافظة.', 'يوفر متجر AQUAVO ميديا فلترة للأحواض، مع توصيل إلى 18 محافظة في العراق.')
 WHERE slug = 'cloudy-aquarium-water-causes-fix';

-- activated-carbon-aquarium-when-to-use · content (2 corrections)
--   REMOVE · Long-term warranties removed. Activated carbon is genuinely stocked, so the availability claim stays.
--   REMOVE · Same blanket warranty; the product itself is real and is kept.
UPDATE blog_posts SET content = replace(replace(content, 'نوصي باستخدام الفحم النشط من ماركات موثوقة، مثل تلك التي تقدمها AQUAVO، التي توفر منتجات عالية الجودة وضمانات طويلة الأمد.', 'نوصي باستخدام الفحم النشط من ماركات موثوقة، مثل الكربون النشط المتوفر في AQUAVO.'), 'نحن في AQUAVO، نسعد بتقديم منتجات عالية الجودة وضمانات طويلة الأمد، بما في ذلك الفحم النشط، لجميع عملائنا في العراق.', 'نحن في AQUAVO، نوفر الكربون النشط ضمن مستلزمات الفلترة لعملائنا في العراق.')
 WHERE slug = 'activated-carbon-aquarium-when-to-use';

-- african-cichlids-best-types-colors · content (1 correction)
--   REMOVE · Warranty and import claims removed; range and the verified delivery term kept.
UPDATE blog_posts SET content = replace(content, 'يمكنك الاستفادة من خدمات وضمانات AQUAVO، التي تضم مجموعة واسعة من المنتجات عالية الجودة والمستوردة، والذي يغطي 18 محافظة في العراق.', 'يمكنك الاستفادة من خدمات AQUAVO، التي تضم مجموعة واسعة من مستلزمات الأحواض، مع توصيل يغطي 18 محافظة في العراق.')
 WHERE slug = 'african-cichlids-best-types-colors';

-- molly-platy-breeding-save-fry · content (1 correction)
--   REMOVE · Warranties for all products removed. العزل والتفريخ is a real category (7 SKUs) and is the one this article needs.
UPDATE blog_posts SET content = replace(content, 'بالإضافة إلى ذلك، فإن AQUAVO توفر ضمانات لجميع منتجاتها، وتقدم خدمة توصيل إلى جميع أنحاء العراق، بما في ذلك 18 محافظة.', 'بالإضافة إلى ذلك، توفر AQUAVO مستلزمات العزل والتفريخ، مع خدمة توصيل إلى 18 محافظة في العراق.')
 WHERE slug = 'molly-platy-breeding-save-fry';

-- fin-rot-treatment-guide · content (2 corrections)
--   REMOVE · Warranties on all products removed; delivery is verified and kept.
--   REMOVE · Same undocumented sourcing claim; replaced with the real category, which is what a fin-rot article should point at.
UPDATE blog_posts SET content = replace(replace(content, 'كما يوفر متجر AQUAVO خدمات التوصيل إلى جميع محافظات العراق البالغ عددها 18 محافظة، ويوفر ضمانات على جميع المنتجات.', 'كما يوفر متجر AQUAVO التوصيل إلى 18 محافظة في العراق.'), 'حيث يُقدم مجموعة واسعة من المنتجات عالية الجودة والمستوردة من أفضل الشركات العالمية.', 'حيث يوفر معالجات المياه وأدوية الأحواض.')
 WHERE slug = 'fin-rot-treatment-guide';

-- fish-keeping-stress-relief-mental-health · content (1 correction)
--   REMOVE · 'Imported from the best companies in the world' has no source. Replaced with categories that exist.
UPDATE blog_posts SET content = replace(content, 'ويقدم ضمانات وخدمات توصيل إلى 18 محافظة في العراق. بالإضافة إلى ذلك، يقدم <strong>AQUAVO</strong> منتجات عالية الجودة ومستوردة من أفضل الشركات في العالم.', 'ويقدم خدمات توصيل إلى 18 محافظة في العراق. بالإضافة إلى ذلك، يقدم <strong>AQUAVO</strong> مستلزمات الأحواض من الفلترة والتهوية ومعالجة المياه.')
 WHERE slug = 'fish-keeping-stress-relief-mental-health';

-- aquarium-soil-volcanic-substrate-secrets · content (2 corrections)
--   REMOVE · Authorised-and-imported-from-the-best-factories plus a blanket warranty. Volcanic rock and aquascaping soil are both genuinely stocked.
--   REMOVE · Quality guarantee and 'all regions' removed; the verified delivery term replaces the vague one.
UPDATE blog_posts SET content = replace(replace(content, 'وتعد منتجات AQUAVO المصرح بها ومستوردة من أفضل المصانع العالمية خياراً مثاليًا لمحبي الأسماك في العراق، مع ضمانات وخدمة توصيل إلى جميع المحافظات الـ 18.', 'وتتوفر التربة والصخور البركانية في AQUAVO، مع خدمة توصيل إلى 18 محافظة في العراق.'), 'يمكنهم الحصول على التربة البركانية وجميع المنتجات اللازمة لإنشاء حوض سمك مثالي من متجر AQUAVO، مع ضمان جودة وخدمة توصيل سريعة إلى جميع المناطق.', 'يمكنهم الحصول على التربة والصخور البركانية من متجر AQUAVO، مع توصيل إلى 18 محافظة في العراق.')
 WHERE slug = 'aquarium-soil-volcanic-substrate-secrets';

-- filter-media-ceramic-rings-bioballs · content (1 correction)
--   REMOVE · Import claim and a superlative. Ceramic rings and filter media are real products, and naming them is both truthful and more useful.
UPDATE blog_posts SET content = replace(content, 'بالإضافة إلى ذلك، نقدم لك مجموعة واسعة من المنتجات المستوردة من أفضل الشركات العالمية، والتي تُعتبر من أفضل الخيارات لآحواض المائية في العراق.', 'بالإضافة إلى ذلك، نقدم مجموعة واسعة من ميديا الفلترة وحلقات السيراميك للأحواض.')
 WHERE slug = 'filter-media-ceramic-rings-bioballs';

-- best-aquarium-store-iraq-2026 · excerpt (1 correction)
--   REMOVE · 'First and biggest' has no source, and 'متخصص في أسماك الزينة' reads as selling the fish. The page's comparison purpose is untouched — only the two unsupported claims go. Flagged to the owner twice as a positioning decision; corrected here because an unsupported superlative is exactly what this pass exists to remove.
UPDATE blog_posts SET excerpt = replace(excerpt, 'تعرف على أول وأكبر متجر إلكتروني متخصص في أسماك الزينة ومستلزمات الأحواض في العراق (AQUAVO) ولماذا يتفوق على الأسواق التقليدية.', 'تعرف على متجر AQUAVO الإلكتروني المتخصص بمستلزمات أحواض الأسماك في العراق، ولماذا يختلف عن الأسواق التقليدية.')
 WHERE slug = 'best-aquarium-store-iraq-2026';

-- Post-flight: titles and publication state may not move, and exactly the
-- drafted rows may change in exactly the drafted columns.
DO $$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n
    FROM blog_posts b JOIN blog_posts_backup_claims_b4_20260902 k USING (id)
   WHERE b.title IS DISTINCT FROM k.title
      OR b.is_published IS DISTINCT FROM k.is_published;
  IF n <> 0 THEN RAISE EXCEPTION '% rows had title/is_published altered', n; END IF;

  SELECT count(*) INTO n
    FROM blog_posts b JOIN blog_posts_backup_claims_b4_20260902 k USING (id)
   WHERE b.content IS DISTINCT FROM k.content;
  IF n <> 14 THEN RAISE EXCEPTION 'expected 14 content rewrites, got %', n; END IF;

  SELECT count(*) INTO n
    FROM blog_posts b JOIN blog_posts_backup_claims_b4_20260902 k USING (id)
   WHERE b.excerpt IS DISTINCT FROM k.excerpt;
  IF n <> 1 THEN RAISE EXCEPTION 'expected 1 excerpt rewrites, got %', n; END IF;
END $$;

COMMIT;
